hmcts/ia-aip-frontend

app/app.ts
app/views/index.html
app/views/layout.html
nodemon.json
package.json
webpack.config.js
yarn.lock

Webpack config and plugins

---

views/layout.html
webpack.config.js

More Webpack configuration, copying assets from govuk-frontend library
```
[ ] Yes
[ X ] No
```

Webpack copying assets

---

app/app.ts
app/controllers/health.ts
app/controllers/index.ts
app/paths.ts
app/routes.ts
app/session.ts
config/custom-environment-variables.json
config/default.json
package.json
test/unit/controllers/health.test.ts
yarn.lock

- Remove health and liveness endpoints from app.ts.
- Removed session setup from app.ts.
- Added test:all to package.js.
- Setup husky to run yarn lint on commit.
- Fixed typo in useReddis to useRedis

Refactor app.ts

---

sonar-project.properties

There was a load of exclusions in the sonar-project.properties. Removed them and fixed issues with the build.

Remove most of the sonar exclusions for this project.

---

app/app-config.ts
app/app.ts
app/server.ts
app/utils/logger.ts
package.json
sonar-project.properties
test/utils/common.ts
webpack/webpack.common.js
yarn.lock

Adding more app configuration
Some refactoring for app and server
```
[ ] Yes
[ X ] No
```

More app configurations and refactoring

---

app/app.ts
app/handlers/error-handler.ts
package.json
yarn.lock

Adding cookie parser middleware
```
[ ] Yes
[ X ] No
```

Adding cookie parser middleware

---

.nycrc
app/assets/scss/_cookie-banner.scss
app/assets/scss/application.scss
client/cookies-banner.ts
client/main.ts
locale/en.json
package.json
sonar-project.properties
test/mocha.opts
test/unit/client/cookies-banner.test.ts
test/unit/client/main.test.ts
views/layout.njk
webpack/webpack.common.js
yarn.lock

Adding cookies banner
- Class to manage whether banner has to be shown or not
- Added cookie bar on the layout
- Added some styling for cookie banner
- Unit Tests
```
[ ] Yes
[ X ] No
```
**Screenshots**

Adding cookies banner

---

app/controllers/index.ts
app/controllers/personal-details-get-names.ts
app/paths.ts
app/routes.ts
app/utils/personal-details-schema.ts
locale/en.json
package.json
test/unit/controllers/get-name-page.test.ts
views/get-names-page.njk
views/layout.njk
yarn.lock

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1190&projectKey=RIA&view=detail&selectedIssue=RIA-1956
First page of personal details
```
[ ] Yes
[ x] No
```

Added get name page

---

app/controllers/idam.ts
app/controllers/index.ts
app/controllers/personal-details-get-names.ts
app/controllers/task-list.ts
app/domain/request.ts
app/session.ts
package.json
test/unit/controllers/get-name-page.test.ts
test/unit/controllers/home-office-details.test.ts
test/unit/controllers/index.test.ts
test/unit/controllers/task-list.test.ts
yarn.lock

Adding express-session types and refactoring controllers to use the types
```
[ ] Yes
[ X ] No
```

Adding @types/express-session and refactoring

---

app/controllers/index.ts
app/controllers/personal-details-get-names.ts
app/controllers/task-list.ts
app/handlers/error-handler.ts
app/server.ts
app/service/s2s-service.ts
app/utils/jwt-utils.ts
app/utils/logger.ts
test/unit/utils/logger.test.ts

N/A
Added helper method to extract logLabel from path.
Should output something like "directory/filename.ts"
```
[ ] Yes
[ x] No
```

Added helper method to extract logLabel from path.

---

app/controllers/home-office-details.ts
app/controllers/personal-details.ts
app/utils/fields-validations.ts
locale/en.json
test/unit/controllers/enter-date.test.ts
test/unit/controllers/home-office-details.test.ts
test/unit/utils/fields-validations.test.ts
views/appeal-application/date-of-birth.njk
views/layout.njk

Refactoring date validations to return an object which keys are the inputs ids and the errors an object can easily serialize on an array for govukErrorSummary to consume.
Also removed dateInput macro in layout and make the necessary changes to make it work with the new dateInput component.
```
[ ] Yes
[ X ] No
```

Refactoring validations and date macros

---

app/controllers/contact-details.ts
app/paths.ts
app/routes.ts
app/utils/fields-validations.ts
locale/en.json
test/unit/controllers/contact-details.test.ts
test/unit/utils/fields-validations.test.ts
views/components/error-components.njk
views/contact-details.njk

https://tools.hmcts.net/jira/browse/RIA-1963
Adds Contact Details Page
Adds Validation
Adds field per Validations
Adds correct logic to highlight the right components on validation failure
```
[ ] Yes
[ x] No
```

RIA-1963: Contact Details

---

app/controllers/personal-details.ts
app/paths.ts
app/utils/fields-validations.ts
locale/en.json
test/unit/controllers/enter-postcode.test.ts
test/unit/controllers/postcode-lookup.test.ts
views/appeal-application/personal-details/enter-address.njk
views/appeal-application/personal-details/postcode-lookup.njk

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1190&projectKey=RIA&view=detail&selectedIssue=RIA-1962
```
[ ] Yes
[ x ] No
```

RIA-1956-Postcode-Lookup

---

app/assets/scss/_evidence-list.scss
app/assets/scss/application.scss
app/controllers/home-office-details.ts
app/paths.ts
test/unit/controllers/home-office-details.test.ts
views/appeal-application/home-office/appeal-late.njk
views/components/evidence-list.njk

https://tools.hmcts.net/jira/browse/RIA-1983
Creating new page 'out of time appeal' for appellant explain reasons why he/she is late, also the ability to upload a file to support his/her answer 
```
[ ] Yes
[ X ] No
```

RIA-1983 - Out of time page

---

app/controllers/check-and-send.ts
app/controllers/dev-next-page.ts
app/controllers/personal-details.ts
app/data/dummy.ts
app/routes.ts
app/utils/fields-validations.ts
app/utils/summary-list.ts
locale/en.json
test/unit/controllers/check-and-send.test.ts
test/unit/controllers/enter-address.test.ts
test/unit/controllers/enter-postcode.test.ts
test/unit/utils/fields-validations.test.ts
test/unit/utils/summary-list.test.ts
types/index.d.ts
views/appeal-application/check-and-send.njk
views/appeal-application/personal-details/enter-address.njk

https://tools.hmcts.net/jira/browse/RIA-1965
Refactored `fields-validation.ts` to remove duplication.
Added summary list utils that helps building the objects needed for the `summaryList` component in check your answers page
Added Check your answers page view.
Added Appeal domain objects initial structure
Added dummy appeal data
Added summary list utils that helps building the objects needed for the `summaryList` component in check your answers page
```
[ ] Yes
[ x] No
```

RIA-1965 - Check your answers

---

app/assets/scss/_success-component.scss
app/assets/scss/application.scss
app/controllers/confirmation-page.ts
app/paths.ts
app/routes.ts
test/unit/controllers/confirmation-page.test.ts
views/confirmation-page.njk

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1190&projectKey=RIA&view=detail&selectedIssue=RIA-1972&quickFilter=7031&quickFilter=7042
Added Success page
```
[ ] Yes
[ x ] No
```

Added success page

---

app/config/idam-config.ts
app/controllers/check-and-send.ts
app/controllers/home-office-details.ts
app/controllers/idam.ts
app/controllers/index.ts
app/controllers/startController.ts
app/data/dummy.ts
app/middleware/initSession.ts
app/paths.ts
app/routes.ts
app/utils/url-utils.ts
test/unit/controllers/home-office-details.test.ts
test/unit/controllers/start.test.ts
test/unit/middleware/initSession.test.ts
test/unit/utils/url-utils.test.ts
types/express/index.d.ts
types/index.d.ts
views/appeal-application/home-office/details.njk

https://tools.hmcts.net/jira/browse/RIA-2066
Refactoring Idam
Init Session Middleware
```
[ ] Yes
[ X ] No
```

Idam refactoring

---

app/controllers/personal-details.ts
package.json
test/e2e/cypress/cypress.json
test/e2e/cypress/fixtures/example.json
test/e2e/cypress/integration/appeal-application/Appeal.feature
test/e2e/cypress/integration/appeal-application/Appeal/appeal.ts
test/e2e/cypress/plugins/index.js
test/e2e/cypress/support/commands.js
test/e2e/cypress/support/index.js
test/unit/utils/logger.test.ts
tsconfig.json
types/express/index.d.ts
yarn.lock

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1190&view=detail&selectedIssue=RIA-2061
e2e tests 
```
[ ] Yes
[ x ] No
```

RIA-2061-E2E-Test

---

app/controllers/contact-details.ts
app/controllers/home-office-details.ts
app/controllers/personal-details.ts
app/data/dummy.ts
app/routes.ts
app/utils/fields-validations.ts
app/utils/regular-expressions.ts
test/unit/controllers/enter-address.test.ts
test/unit/controllers/enter-postcode.test.ts
test/unit/controllers/postcode-lookup.test.ts
test/unit/utils/fields-validations.test.ts
tsconfig.json
types/index.d.ts
views/appeal-application/personal-details/enter-address.njk
views/appeal-application/personal-details/enter-postcode.njk
views/appeal-application/personal-details/postcode-lookup.njk

Refactor app to save data in session
```
[ ] Yes
[ X ] No
```

Refactoring app to save data in session Part 4

---

app/controllers/home-office-details.ts
app/controllers/personal-details.ts
app/routes.ts
app/service/update-appeal-service.ts
locale/en.json
test/unit/controllers/enter-address.test.ts
test/unit/controllers/enter-date.test.ts
test/unit/controllers/enter-postcode.test.ts
test/unit/controllers/get-name-page.test.ts
test/unit/controllers/home-office-details.test.ts
test/unit/controllers/nationatily-page.test.ts
test/unit/controllers/postcode-lookup.test.ts
test/unit/service/update-appeal-service.test.ts
types/index.d.ts
views/appeal-application/home-office/details.njk

Save values in CCD for 
- homeOfficeReferenceNumber
- homeOfficeDecisionDate
- appellantGivenNames
- appellantFamilyName
- appellantDateOfBirth
https://tools.hmcts.net/jira/browse/RIA-2163
```
[ ] Yes
[X] No
```

Ria 2163 setting ccd values

---

locale/en.json
views/appeal-application/type-of-appeal.njk

https://tools.hmcts.net/jira/browse/RIA-1966
Updates text and descriptions to align with V6 of the prototype
```
[ ] Yes
[x ] No
```

RIA-1964: Updated text to v6

---

app/controllers/home-office-details.ts
app/controllers/personal-details.ts
app/data/dummy.ts
app/utils/fields-validations.ts
locale/en.json
test/mock/idam/services/getDetails.js
test/unit/controllers/check-and-send.test.ts
test/unit/controllers/contact-details.test.ts
test/unit/controllers/enter-address.test.ts
test/unit/controllers/enter-date.test.ts
test/unit/controllers/enter-postcode.test.ts
test/unit/controllers/get-name-page.test.ts
test/unit/controllers/home-office-details.test.ts
test/unit/controllers/nationatily-page.test.ts
test/unit/utils/fields-validations.test.ts
types/index.d.ts
views/appeal-application/personal-details/enter-address.njk
views/appeal-application/personal-details/name.njk
views/appeal-application/personal-details/nationality.njk

Allow the user to enter personal details. Updated validation.
https://tools.hmcts.net/jira/browse/RIA-1956
```
[ ] Yes
[X] No
```

Ria 1956 personal details

---

app/controllers/home-office-details.ts
app/controllers/personal-details.ts
app/service/update-appeal-service.ts
app/utils/fields-validations.ts
locale/en.json
test/unit/controllers/contact-details.test.ts
test/unit/controllers/get-name-page.test.ts
test/unit/controllers/home-office-details.test.ts
test/unit/controllers/nationatily-page.test.ts
test/unit/service/update-appeal-service.test.ts
test/unit/utils/fields-validations.test.ts
types/index.d.ts
views/appeal-application/home-office/details.njk

Fix home office reference number validation
https://tools.hmcts.net/jira/browse/RIA-1953
```
[ ] Yes
[X] No
```

Ria 1953 ho details

---

.gitignore
app/controllers/type-of-appeal.ts
app/routes.ts
app/service/update-appeal-service.ts
app/utils/fields-validations.ts
locale/en.json
test/unit/controllers/type-of-appeal.test.ts
test/unit/service/update-appeal-service.test.ts

https://tools.hmcts.net/jira/browse/RIA-1964
Saves appeal type in CCD.
Correcting error message to "Select at least one of the appeal types" as specified on the AC
Updating tests
Adds `.env` to `.gitignore`
```
[ ] Yes
[x ] No
```

RIA-1964 - FIX

---

app/controllers/check-and-send.ts
app/controllers/personal-details.ts
app/data/dummy.ts
app/routes.ts
app/service/update-appeal-service.ts
app/utils/address-utils.ts
app/utils/fields-validations.ts
app/utils/tasks-utils.ts
config/custom-environment-variables.json
config/default.json
locale/en.json
package.json
test/unit/controllers/enter-address.test.ts
test/unit/controllers/enter-postcode.test.ts
test/unit/controllers/postcode-lookup.test.ts
test/unit/utils/address-utils.test.ts
test/unit/utils/task-utils.test.ts
types/index.d.ts
views/appeal-application/personal-details/enter-address.njk
yarn.lock

- Use the reform OS-places client library to lookup the postcode a user
has entered.
- Add number of addresses found to drop down list.
- Fixed changed postcode link on manual address page
- Save address to CCD.
https://tools.hmcts.net/jira/browse/RIA-1962
```
[ ] Yes
[X] No
```

RIA-1962 Enter Address Details

---

views/appeal-application/personal-details/nationality.njk

Fix missing label for nationality
https://tools.hmcts.net/jira/browse/RIA-1956
```
[ ] Yes
[X] No
```

RIA-1956 Add label to nationality field

---

app/service/update-appeal-service.ts
test/unit/service/update-appeal-service.test.ts

Removed loading the appellants given name and family name from their IDAM details.

Removed loading the appellants given name and family name from their IDAM details.

---

app/assets/scss/application.scss
app/controllers/home-office-details.ts
app/controllers/personal-details.ts
app/utils/fields-validations.ts
locale/en.json
test/unit/controllers/enter-date.test.ts
test/unit/controllers/home-office-details.test.ts
test/unit/utils/fields-validations.test.ts
views/appeal-application/home-office/appeal-late.njk
views/appeal-application/home-office/details.njk
views/appeal-application/home-office/letter-sent.njk
views/appeal-application/personal-details/date-of-birth.njk

https://tools.hmcts.net/jira/browse/RIA-1953
Fixing bugs on Home office details section
- adding date component from GDS frontend library
- adding and fixing bug for date in the future
- adding alt text to image
- image is now responsive
```
[ ] Yes
[ X ] No
```

Home Office bugs refactoring

---

app/controllers/home-office-details.ts
app/utils/fields-validations.ts
test/unit/controllers/enter-date.test.ts
test/unit/utils/fields-validations.test.ts

https://tools.hmcts.net/jira/browse/RIA-1953
Fixing validation bug and home office ref number update
```
[ ] Yes
[ X ] No
```

Fixing bugs Home Office details

---

config/default.json
config/preview.json
config/test.json
package.json

Enable redis for local dev.

---

app/controllers/check-and-send.ts
test/unit/controllers/check-and-send.test.ts

Fixes 404 when clicking on change home-office details href link
```
[ ] Yes
[x ] No
```

RIA-1965: Fix

---

Jenkinsfile_CNP
charts/ia-aip-frontend/values.preview.template.yaml
config/default.json
config/preview.json

Trying to get the pr environments working so setting up the environment variables.

Set env variables for AKS preview

---

app/controllers/personal-details.ts
app/utils/address-utils.ts
locale/en.json
test/unit/controllers/enter-address.test.ts
test/unit/controllers/enter-postcode.test.ts
test/unit/controllers/nationatily-page.test.ts
test/unit/utils/address-utils.test.ts
views/appeal-application/personal-details/enter-address.njk
views/appeal-application/personal-details/enter-postcode.njk

lookup if they want tio enter their address manually.
Also if you have saved the address already go directly to the enter
address page rather than postcode lookup.

Allow users to go directly to the enter address page from postcode

---

charts/ia-aip-frontend/values.preview.template.yaml

Fix pr environment

---

views/confirmation-page.njk

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1190&projectKey=RIA&view=detail&selectedIssue=RIA-1972
Remove back button from confirmation page.
```
[ ] Yes
[ x ] No
```

remove back button from page

---

views/appeal-application/home-office/details.njk
views/appeal-application/home-office/letter-sent.njk
views/appeal-application/personal-details/date-of-birth.njk

https://tools.hmcts.net/jira/browse/RIA-1953
Adding contact us block to letter sent and details page
Date component showing all the errors as error summary component
```
[ ] Yes
[ X ] No
```

Adding contact us to HO pages, error message on date component

---

.gitignore
Jenkinsfile_CNP
codecept.functional.js
config/default.json
config/test.json
package.json
test/e2e-test/features/basic.feature
test/e2e-test/pages/contact-details/contact-details.js
test/e2e-test/pages/helper-functions.js
test/e2e-test/pages/personal-details/personal-details.js
test/e2e-test/pages/sign-in.js
test/e2e-test/pages/type-of-appeal/type-of-appeal.js

- Fix changes between tests and app
- Make e2e test create a users each time
- Pass in urls from Jenkins as environment variables

Fix e2e tests and set them up tyo run as part of the build.

---

package.json
test/e2e-test/pages/helper-functions.js

Pushlish screenshots when tests fail

Fix not publishing functional test output when it fails

---

package.json
test/e2e-test/pages/helper-functions.ts
test/mock/idam/services/login-page.js
views/appeal-application/task-list.njk

Changes so functional tests can be run in local against mocks
```
[ ] Yes
[ X ] No
```

Changes to run functional tests in local

---

app/utils/fields-validations.ts
extensions/joi/mobile-number.ts
locale/en.json
package.json
test/unit/extensions/mobile-number.test.ts
test/unit/utils/fields-validations.test.ts
yarn.lock

https://tools.hmcts.net/jira/browse/RIA-1963
https://tools.hmcts.net/jira/browse/RIA-2280
**RIA-1963:** Extends Joi validation with a custom extension that check for mobile phones and formats them using google-libphonenumber.
Changed error message wording.
Added tests.
**RIA-2280:** Using a Unicode char as address for email should not be allowed. 
Tighten validation to prohibit Unicode emails.
```
[ ] Yes
[x ] No
```

RIA 1963 & RIA-2280 - Mobile Phone Validation Extension & Unicode Email Validation

---

app/controllers/check-and-send.ts
app/controllers/contact-details.ts
app/controllers/home-office-details.ts
app/controllers/personal-details.ts
app/controllers/type-of-appeal.ts
test/unit/controllers/check-and-send.test.ts
test/unit/controllers/contact-details.test.ts
test/unit/controllers/enter-address.test.ts
test/unit/controllers/enter-dob.test.ts
test/unit/controllers/enter-name-page.test.ts
test/unit/controllers/enter-postcode.test.ts
test/unit/controllers/home-office-details.test.ts
test/unit/controllers/nationatily-page.test.ts
test/unit/controllers/postcode-lookup.test.ts
test/unit/controllers/type-of-appeal.test.ts
views/layout.njk

https://tools.hmcts.net/jira/browse/RIA-2156
Refactoring back button functionality
```
[ ] Yes
[ X ] No
```

RIA-2156: Refactoring back button

---

app/controllers/personal-details.ts
app/utils/url-utils.ts
test/unit/controllers/enter-address.test.ts
test/unit/controllers/enter-postcode.test.ts
test/unit/controllers/postcode-lookup.test.ts
types/index.d.ts

https://tools.hmcts.net/jira/browse/RIA-2282
Fix for Address bug
```
[ ] Yes
[ X ] No
```

RIA-2282: Address bug fix

---

app/app.ts
package.json
yarn.lock

Recreated branch as merge hell

Ria 2321 setup helmet 2

---

app/app.ts
app/middleware/xss-middleware.ts
package.json
test/unit/middleware/xss-middleware.test.ts
yarn.lock

Added middleware that will sanitize all form params using DOMPurify
and not allow any html tags through.
https://tools.hmcts.net/jira/browse/RIA-2256
```
[ ] Yes
[X] No
```

RIA-2256 XSS middleware

---

README.md
app/app.ts
app/routes.ts
codecept.e2e.js
config/custom-environment-variables.json
config/default.json
package.json
test/e2e-test/pages/helper-functions.ts
test/functional/bootstrap.ts
test/functional/features/out-of-time-appeal.feature
test/functional/features/reason-for-appeal.feature
test/mock/postcode-lookup/dysonSetup.js
test/mock/postcode-lookup/services/postcodeLookup.js

Functional tests were exiting with exit code 0 so always passed.

Fix functional tests

---

app/controllers/personal-details.ts
app/handlers/error-handler.ts
app/middleware/session-middleware.ts
app/utils/nationalities.ts
app/utils/url-utils.ts
locale/en.json
test/unit/controllers/nationatily-page.test.ts
test/unit/utils/nationalities.test.ts
views/appeal-application/home-office/details.njk
views/appeal-application/personal-details/enter-address.njk
views/appeal-application/personal-details/enter-postcode.njk
views/appeal-application/personal-details/name.njk
views/components/date-component.njk
views/layout.njk
views/start.njk

Changes all templates and controllers to get content from en.json
https://tools.hmcts.net/jira/browse/RIA-2059
```
[ ] Yes
[X] No
```

Ria 2059 localisations

---

app/middleware/logger.ts

Log stack traces with errors

---

app/controllers/contact-details.ts
app/utils/fields-validations.ts
test/unit/controllers/contact-details.test.ts
test/unit/utils/fields-validations.test.ts

There were bugs in the validation of the contact details simplified the
logic for validation and added some tests.
https://tools.hmcts.net/jira/browse/RIA-2400
```
[ ] Yes
[X] No
```

RIA-2400 Contact details validation

---

app/controllers/check-and-send.ts
test/unit/controllers/check-and-send.test.ts

https://tools.hmcts.net/jira/browse/RIA-2379
```
[ ] Yes
[X] No
```

RIA-2379 Corrected late appeal text on check your answers page.

---

app/utils/fields-validations.ts
locale/en.json
test/unit/controllers/type-of-appeal.test.ts
views/appeal-application/type-of-appeal.njk

Change select appeal type to radio buttons as you can only select one.
Changed validation to reflect this.
https://tools.hmcts.net/jira/browse/RIA-1964
```
[ ] Yes
[X] No
```

Ria 1964 select appeal type

---

app/service/update-appeal-service.ts
test/unit/service/update-appeal-service.test.ts
types/caseData.d.ts

Bug From:
https://tools.hmcts.net/jira/browse/RIA-1967
Adds a new field appellantHasFixedAddress.
Decision was taken to assume that contact addresses are fixed.
**This PR Requires the following ccd-definition: https://github.com/hmcts/ia-ccd-definitions/pull/46**
```
[ ] Yes
[x ] No
```

RIA-1967 - Bug Fix

---

app/controllers/home-office-details.ts
app/service/update-appeal-service.ts
test/unit/service/update-appeal-service.test.ts
types/caseData.d.ts

https://tools.hmcts.net/jira/browse/RIA-2412
Integrating out of time appeal reason with CCD
```
[ ] Yes
[ X ] No
```

RIA-2412: Integrating out of time with CCD

---

locale/en.json

https://tools.hmcts.net/jira/browse/RIA-2381
Copy change: Removes the word 'below' from late appeal page.
```
[ ] Yes
[x ] No
```

RIA-2381: Copy change

---

app/controllers/eligibility.ts
app/controllers/startController.ts
app/paths.ts
app/routes.ts
app/utils/fields-validations.ts
locale/en.json
package.json
test/e2e-test/features/basic.feature
test/e2e-test/pages/eligibility-questions/eligibility-question-page.ts
test/e2e-test/pages/eligibility-questions/eligible-page.ts
test/e2e-test/pages/eligibility-questions/ineligible-page.ts
test/e2e-test/pages/sign-in.ts
test/e2e-test/step_definitions/steps.ts
test/functional/features/eligibility-questions.feature
test/unit/controllers/eligibility.test.ts
test/unit/utils/fields-validations.test.ts
views/eligibility-question.njk
views/eligibility/eligibility-question.njk
views/eligibility/eligible-page.njk
views/eligibility/ineligible-page.njk
views/start.njk

Eligibility questions when starting to use the service
https://tools.hmcts.net/jira/browse/RIA-2425
https://tools.hmcts.net/jira/browse/RIA-2426
https://tools.hmcts.net/jira/browse/RIA-2408
https://tools.hmcts.net/jira/browse/RIA-2424
```
[ ] Yes
[X] No
```

Ria 2408 eligibility questions

---

charts/ia-aip-frontend/values.yaml

RIA-2414 Setup AKS

---

app/controllers/out-of-time.ts
app/utils/fields-validations.ts
config/default.json
locale/en.json
test/unit/utils/fields-validations.test.ts
views/appeal-application/home-office/appeal-late.njk

https://tools.hmcts.net/jira/browse/RIA-2385
Adding a character limit to the textarea so appealants cant write more than 50000 characters
Adding the missing title to error summary component
```
[ ] Yes
[ X ] No
```

RIA-2385: Out of time textarea limit

---

locale/en.json

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1190&projectKey=RIA&view=detail&selectedIssue=RIA-2464&quickFilter=7042
Contact us update and confirmation page update
```
[ ] Yes
[ x ] No
```

Contact change

---

Jenkinsfile_nightly
test/functional/bootstrap-all.ts

https://tools.hmcts.net/jira/browse/RIA-2203
Refactoring cron job so nightly pipeline is only executed at midnight
```
[ ] Yes
[ X ] No
```

Nightly pipeline cron refactoring

---

Jenkinsfile_nightly
codecept.crossbrowser.js

https://tools.hmcts.net/jira/browse/RIA-2203
Adding AAT testing URL
```
[ ] Yes
[ X ] No
```

Nightly pipeline add AAT TEST_URL

---

Jenkinsfile_nightly

Fixing typo on Jenkings nightly file
```
[ ] Yes
[ X ] No
```

RIA-2203: Fixing typo on jenkins file

---

app/controllers/eligibility.ts
locale/en.json
test/e2e-test/features/basic.feature
test/functional/features/eligibility-questions.feature
test/unit/controllers/eligibility.test.ts

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1190&projectKey=RIA&view=detail&selectedIssue=RIA-2549&quickFilter=7042
Amended questions
```
[ ] Yes
[ x ] No
```

Eligibility Questions Amend

---

test/mock/ccd/mock-case-data/data/appeal-submitted.js
test/mock/ccd/mock-case-data/data/awaiting-reasons-for-appeal.js
test/mock/ccd/mock-case-data/data/partial-appeal-started.js
test/mock/ccd/mock-case-data/index.js
test/mock/ccd/mock-case-data/index.ts

Translating typescript files used in mocks to js.

Translating typescript files used in mocks to js.

---

Jenkinsfile_CNP

Disable ASE

---

Jenkinsfile_nightly
security.sh

Ria 2202 zap scan

---

app/app.ts
package.json
types/express/index.d.ts
views/appeal-application/check-and-send.njk
views/appeal-application/contact-details.njk
views/appeal-application/home-office/appeal-late.njk
views/appeal-application/home-office/details.njk
views/appeal-application/home-office/letter-sent.njk
views/appeal-application/personal-details/date-of-birth.njk
views/appeal-application/personal-details/enter-address.njk
views/appeal-application/personal-details/enter-postcode.njk
views/appeal-application/personal-details/name.njk
views/appeal-application/personal-details/nationality.njk
views/appeal-application/personal-details/postcode-lookup.njk
views/appeal-application/type-of-appeal.njk
views/eligibility/eligibility-question.njk
views/reasons-for-appeal/check-and-send-page.njk
views/reasons-for-appeal/reason-for-appeal-page.njk
views/reasons-for-appeal/supporting-evidence-page.njk
views/reasons-for-appeal/supporting-evidence-upload-page.njk
yarn.lock

Use the csurf library and add a csrf token to all the post requests.
For multi part forms add the csrf token to the url as it is being
checked before the multipart form is processed
```
[ ] Yes
[ ] No
```

Setup CSRF protection

---

app/app.ts
charts/ia-aip-frontend/Chart.yaml
charts/ia-aip-frontend/values.yaml
config/custom-environment-variables.json

Set session cookie to be secure
Set trust proxy so we can enable secure cookies
```
[ ] Yes
[ ] No
```

RIA-2697 Set secure attribute on session cookie

---

app/app.ts
app/session.ts
app/utils/url-utils.ts
config/default.json
locale/en.json
package.json
views/layout.njk
yarn.lock

Ria 2702 relative path confusion

---

test/e2e-test/pages/error-pages/404-error-page.ts
test/unit/utils/validations/fields-validations.test.ts

Fix leap year bug

---

views/start.njk

Changed from 'Already a user' text on start page from  b tag to h2
https://tools.hmcts.net/jira/browse/RIA-2724
```
[ ] Yes
[ x ] No
```

H2 missing

---

locale/en.json
views/layout.njk

Adding feedback survey link
```
[ ] Yes
[ X ] No
```

RIA-2602: Adding feedback survey link to beta phase banner

---

app/assets/scss/_cookie-banner.scss

https://tools.hmcts.net/jira/browse/RIA-2722
- Fixing cookies banner contrast accessibility bug
```
[ ] Yes
[ X ] No
```

RIA-2722: Fixing cookies banner contrast accessibility bug

---

views/appeal-application/personal-details/nationality.njk

https://tools.hmcts.net/jira/browse/RIA-2747
Adding label to nationality select
```
[ ] Yes
[ X ] No
```

RIA-2747: Adding label to nationality page

---

locale/en.json
test/e2e-test/pages/overview-page/overview-page.ts
views/application-overview.njk

https://tools.hmcts.net/jira/browse/RIA-2746
Fixing contact us phone number in overview page
```
[ ] Yes
[ X ] No
```

RIA-2746: Fixing contact us phone number in overview page

---

README.md
app/controllers/appeal-application/confirmation-page.ts
app/utils/application-state-utils.ts
app/utils/event-deadline-date-finder.ts
codecept.functional.js
config/custom-environment-variables.json
config/default.json
locale/en.json
test/e2e-test/pages/appeal-sent/appeal-sent.ts
test/e2e-test/pages/check-and-send/check-and-send.ts
test/e2e-test/pages/common/common.ts
test/e2e-test/pages/overview-page/overview-page.ts
test/e2e-test/pages/reasons-for-appeal/reasons-for-appeal-confirmation.ts
test/e2e-test/step_definitions/steps.ts
test/functional/features/overview-page.feature
test/functional/features/reason-for-appeal.feature
test/functional/features/submission-page.feature
test/mock/ccd/services/otherEventStartEvent.js
test/mock/ccd/services/otherEventSubmitEvent.js
test/unit/controllers/confirmation-page.test.ts
test/unit/utils/application-state-utils.test.ts
test/unit/utils/event-deadline-date-finder.test.ts
views/confirmation-page.njk

Updated the copt to say a TCW will try to get back to you by a set date but this may take longer.
https://tools.hmcts.net/jira/browse/RIA-2642

Ria 2642 Updated response dates copy

---

app/handlers/error-handler.ts

Check we have an accept header before trying to display 400 and 500

---

views/components/overview-timeline.njk

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1190&projectKey=RIA&view=detail&selectedIssue=RIA-2850&quickFilter=7042
Added timeline padding
```
[ ] Yes
[ ] No
```

RIA-2850: added padding on timline complete

---

package.json

Disabling temporarily audit process so bug fixes can be merged quicker
```
[ ] Yes
[ X ] No
```

Disabling audit temporarily

---

app/controllers/guidance-page.ts
test/unit/controllers/guidance-page.test.ts

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1190&projectKey=RIA&view=detail&selectedIssue=RIA-2847&quickFilter=7042
Added contact us module
```
[ ] Yes
[ ] No
```

RIA-2847: added contact us module

---

app/controllers/appeal-application/check-and-send.ts
app/controllers/detail-viewers.ts

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1190&projectKey=RIA&view=detail&selectedIssue=RIA-2863
Added title for late appeal support
```
[ ] Yes
[ ] No
```

RIA-2863: fixed supporting evidence title

---

app/controllers/reasons-for-appeal/check-and-send.ts
test/unit/controllers/reasons-for-appeal/check-and-send.test.ts

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1190&projectKey=RIA&view=detail&selectedIssue=RIA-2758&quickFilter=7042
CYA save for later fix
```
[ ] Yes
[ ] No
```

RIA-2758-CYA save for later button fix

---

locale/en.json

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1190&projectKey=RIA&view=detail&selectedIssue=RIA-2901&quickFilter=7042
Text spacing update
```
[ ] Yes
[ x ] No
```

RIA-2901-home-office-documents-spacing-update

---

locale/en.json
views/appeal-application/check-and-send.njk
views/application-overview.njk
views/reasons-for-appeal/reason-for-appeal-page.njk

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1190&projectKey=RIA&view=detail&selectedIssue=RIA-2803&quickFilter=7042
Updated contact us email
```
[ ] Yes
[ ] No
```

RIA-2803-Update contact us

---

locale/en.json
views/confirmation-page.njk

https://tools.hmcts.net/jira/browse/RIA-2604
Cleaning deadlinks
Remove repeated bullet point in confirmation page
```
[ ] Yes
[ X ] No
```

Ria 2604: deadlink cleanup

---

Jenkinsfile_CNP
app/app.ts
app/controllers/session.ts
app/routes.ts
charts/ia-aip-frontend/Chart.yaml
charts/ia-aip-frontend/values.aat.template.yaml
charts/ia-aip-frontend/values.preview.template.yaml
client/session-timeout.ts
package.json
test/unit/client/session-timeout.test.ts
test/unit/controllers/session.test.ts

https://tools.hmcts.net/jira/browse/RIA-2826
Timeout bug fix
```
[ ] Yes
[ X ] No
```

Ria 2826 session timeout bug

---

locale/en.json
test/unit/controllers/application-overview.test.ts

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1190&projectKey=RIA&view=detail&selectedIssue=RIA-2861&quickFilter=7042
Fixed home office link
```
[ ] Yes
[ ] No
```

RIA-2861: fixed home office link

---

infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/output.tf
infrastructure/preview.tfvars
infrastructure/prod.tfvars
infrastructure/sprod.tfvars
infrastructure/variables.tf

tf clenaup

---

app/controllers/application-overview.ts
test/unit/controllers/application-overview.test.ts

https://tools.hmcts.net/jira/browse/RIA-2876
- Adds Appellant name to the timeline overview when provided instead of pulling the name from IDAM.
- Updated tests
```
[ ] Yes
[x ] No
```

RIA-2876: Appelant Name Change [NEW BRANCH]

---

app/utils/application-state-utils.ts
test/unit/controllers/application-overview.test.ts
views/components/overview-timeline.njk

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1190&projectKey=RIA&view=detail&selectedIssue=RIA-2857&quickFilter=7042
Change description
Fix '?' and tribunal link
```
[ ] Yes
[ ] No
```

RIA-2857: fixed tribunal app link

---

Jenkinsfile_CNP
Jenkinsfile_nightly
config/custom-environment-variables.json
config/default.json
config/e2e-local.json
package.json
test/e2e-test/features/basic.feature
test/e2e-test/pages/check-and-send/check-and-send.ts
test/e2e-test/pages/helper-functions.ts
test/e2e-test/service/authentication-service.ts
test/e2e-test/service/case-progression-service.ts
test/e2e-test/service/ccd-service.ts
test/e2e-test/service/idam-service.ts
test/e2e-test/service/s2s-service.ts
test/e2e-test/step_definitions/steps.ts

https://tools.hmcts.net/jira/browse/RIA-2899
**RIA-2899:**
- Completes the e2e tests.
- Adds Idam, s2s and ccd services that allow calling the case-worker endpoints.
- Adds case-progression to perform actions as TCW and HO.
- Adds e2e-local config.
- Adds test users to the Jenkins_CNP file
- Fixes an issue where microservice name was not being passed in as an env var
```
[ ] Yes
[ x] No
```

RIA-2899: Completes the e2e tests (New Branch)

---

app/controllers/reasons-for-appeal/reason-for-appeal.ts
app/service/update-appeal-service.ts
app/utils/utils.ts
test/unit/service/update-appeal-service.test.ts
test/unit/utils/utils.test.ts
types/caseData.d.ts
types/index.d.ts

Add a date uploaded and a description to the reasons for appeal
evidence. This can then be displayed in CCD to help the TCW handle the
reasons for appeal.
https://tools.hmcts.net/jira/browse/RIA-2866

RIA-2866 TCW handle reasons for appeal

---

app/controllers/appeal-application/check-and-send.ts
app/controllers/reasons-for-appeal/reason-for-appeal.ts
app/service/update-appeal-service.ts
client/session-timeout.ts

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1190&projectKey=RIA&view=detail&selectedIssue=RIA-2213
Sonarcloud updates
```
[ ] Yes
[ ] No
```

RIA-2213-sonarcloud fixes

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/RIA-2963
Upgrading packages to fix vulnerabilities:
- jsdom
```
[ ] Yes
[ X ] No
```

RIA-2963: Upgrade jsdom package

---

README.md

N/A
Updated README.md with configuration needed to start the app.
```
[ ] Yes
[ x] No
```

Updated README.md with configuration needed to start the app.

---

codecept.setup.js
package.json
test/e2e-test/setup/reasons_for_appeal_requested.feature

Quick and dirty way to setup a user who has submitted an appeal and the
TCW has requested their reasons for appeal

Setup user

---

views/layout.njk

https://tools.hmcts.net/jira/browse/RIA-2056
Adding tags for Google Analytics and Google Tag Manager
```
[ ] Yes
[ X ] No
```

RIA-2056: Adding GTM and GA tags to layout

---

app/controllers/ask-for-more-time/ask-for-more-time.ts
app/controllers/reasons-for-appeal/check-and-send.ts
app/middleware/journeyAllowed-middleware.ts
test/unit/controllers/ask-for-more-time.test.ts
test/unit/controllers/reasons-for-appeal/check-and-send.test.ts
test/unit/middleware/journeyAllowed-middleware.test.ts
views/components/evidence-list.njk

reasons for appeal upload page
reasons for appeal check you answers page
ask for more time upload page
ask for more time check you answers page
https://tools.hmcts.net/jira/browse/RIA-3005
```
[ ] Yes
[ ] No
```

RIA-3005 Add links to evidence on

---

locale/en.json
views/appeal-application/home-office/appeal-late.njk
views/reasons-for-appeal/supporting-evidence-upload-page.njk
views/upload-evidence/evidence-upload-page.njk

Ria 2872 evidence upload screen wording 2

---

app/app-config.ts
app/app.ts
app/config/idam-config.ts
package.json
yarn.lock

Ria 2934 logging login

---

app/assets/scss/_save-buttons-component.scss
app/assets/scss/application.scss
app/controllers/appeal-application/personal-details.ts
views/appeal-application/home-office/appeal-late.njk
views/appeal-application/home-office/details.njk
views/appeal-application/home-office/letter-sent.njk
views/appeal-application/personal-details/enter-address.njk
views/appeal-application/personal-details/enter-postcode.njk
views/appeal-application/personal-details/name.njk
views/appeal-application/personal-details/postcode-lookup.njk
views/application-overview.njk
views/ask-for-more-time/ask-for-more-time.njk
views/detail-viewers/appeal-details-viewer.njk
views/detail-viewers/reasons-for-appeal-details-viewer.njk
views/eligibility/eligibility-question.njk
views/eligibility/eligible-page.njk
views/eligibility/ineligible-page.njk
views/footer/cookies.njk
views/footer/privacy-policy.njk
views/footer/terms-and-conditions.njk
views/forbidden/forbidden.njk
views/guidance-pages/guidance-page.njk
views/layout.njk
views/reasons-for-appeal/check-and-send-page.njk
views/session/session-ended.njk

https://tools.hmcts.net/jira/browse/RIA-2877
Refactoring views so fieldset is used everywhere we have inputs. In other cases, h1 with govuk-heading-xl class should be used
```
[ ] Yes
[ X ] No
```

RIA-2877: Refactoring input views to use fieldset instead of headers

---

client/session-timeout.ts
test/unit/client/session-timeout.test.ts

https://tools.hmcts.net/jira/browse/RIA-3183

RIA-3183 Fix session timeout not displaying

---

app/controllers/reasons-for-appeal/check-and-send.ts
app/service/update-appeal-service.ts
test/unit/service/update-appeal-service.test.ts
types/caseData.d.ts
types/index.d.ts

https://tools.hmcts.net/jira/browse/RIA-2972
Branch - RIA-2972-reaons-for-appeal-display 
Added field for RFA upload date
```
[ ] Yes
[ x ] No
```

added upload date

---

app/controllers/clarifying-questions/question-page.ts
app/controllers/clarifying-questions/supporting-evidence-question-page.ts
app/controllers/clarifying-questions/supporting-evidence.ts
app/paths.ts
app/routes.ts
app/service/update-appeal-service.ts
test/functional/features/clarifying-questions.feature
test/unit/controllers/clarifying-questions/question-page.test.ts
test/unit/controllers/clarifying-questions/questions-list.test.ts
test/unit/controllers/clarifying-questions/supporting-evidence-question-page.test.ts
test/unit/controllers/clarifying-questions/supporting-evidence.test.ts
test/unit/service/update-appeal-service.test.ts
types/caseData.d.ts
types/index.d.ts
views/components/radio-button-question.njk
views/guidance-pages/guidance-page.njk
views/upload-evidence/supporting-evidence-question-page.njk
views/upload-evidence/supporting-evidence-upload-page.njk

https://tools.hmcts.net/jira/browse/RIA-2310
Upload supporting evidences for CQ
```
[ ] Yes
[ X ] No
```

RIA-2310: Upload supporting evidences for CQ

---

app/controllers/clarifying-questions/check-and-send.ts
app/service/update-appeal-service.ts
test/e2e-test/setup/reasons_for_appeal_requested.feature
test/unit/controllers/clarifying-questions/anything-else-answer.test.ts
test/unit/controllers/clarifying-questions/anything-else-question.test.ts
test/unit/controllers/clarifying-questions/check-and-send.test.ts
test/unit/controllers/clarifying-questions/question-page.test.ts
test/unit/controllers/clarifying-questions/questions-list.test.ts
test/unit/controllers/clarifying-questions/supporting-evidence-question-page.test.ts
test/unit/controllers/clarifying-questions/supporting-evidence.test.ts
test/unit/service/update-appeal-service.test.ts
types/index.d.ts

Add the date sent, due date and date responded to the clarifying
questions.
https://tools.hmcts.net/jira/browse/RIA-3090

RIA-3090 Dates clarifying questions

---

app/controllers/clarifying-questions/anything-else-answer.ts
app/controllers/clarifying-questions/question-page.ts
app/service/update-appeal-service.ts
test/functional/features/clarifying-questions.feature
test/unit/controllers/clarifying-questions/anything-else-answer.test.ts
test/unit/controllers/clarifying-questions/anything-else-question.test.ts
test/unit/service/update-appeal-service.test.ts

https://tools.hmcts.net/jira/browse/RIA-2313
Adding evidences to anything else question
```
[ ] Yes
[ X ] No
```

RIA-2313: anything else uploading evidences

---

app/controllers/clarifying-questions/anything-else-answer.ts
app/controllers/clarifying-questions/check-and-send.ts
app/controllers/clarifying-questions/question-page.ts
app/controllers/clarifying-questions/supporting-evidence.ts
app/controllers/upload-evidence/upload-evidence-controller.ts
test/functional/features/clarifying-questions.feature
test/unit/controllers/clarifying-questions/anything-else-answer.test.ts
test/unit/controllers/clarifying-questions/check-and-send.test.ts
test/unit/controllers/clarifying-questions/question-page.test.ts
test/unit/controllers/clarifying-questions/supporting-evidence.test.ts
test/unit/controllers/upload-evidence-controller.test.ts
views/clarifying-questions/question-page.njk

https://tools.hmcts.net/jira/browse/RIA-2979
Added save for later button for questions
```
[ ] Yes
[ x ] No
```

RIA-2979-save-for-later

---

app/controllers/appeal-application/check-and-send.ts
app/controllers/appeal-application/contact-details.ts
app/controllers/appeal-application/home-office-details.ts
app/controllers/appeal-application/task-list.ts
app/controllers/cma-requirements/task-list.ts
app/middleware/session-middleware.ts
app/routes.ts
app/service/update-appeal-service.ts
app/utils/tasks-utils.ts
app/utils/timeline-utils.ts
app/utils/utils.ts
charts/ia-aip-frontend/Chart.yaml
charts/ia-aip-frontend/requirements.yaml
test/mock/ccd/services/otherEventSubmitEvent.js
test/unit/controllers/check-and-send.test.ts
test/unit/controllers/confirmation-page.test.ts
test/unit/controllers/contact-details.test.ts
test/unit/controllers/home-office-details.test.ts
test/unit/middleware/session-middleware.test.ts
test/unit/mockData/mock-appeal.ts
test/unit/service/update-appeal-service.test.ts
test/unit/utils/task-utils.test.ts
test/unit/utils/utils.test.ts
types/index.d.ts

https://tools.hmcts.net/jira/browse/RIA-3251
updateAppealService submitEvent refactored
postHomeOfficeDetails endpoint refactored using above mentioned method and updating session with ccdCase updated.
Remove 'tasks' from the session and moved logic to the controller
```
[ ] Yes
[ X ] No
```

Ria 3251 refactoring submit event

---

app/service/update-appeal-service.ts
test/unit/service/update-appeal-service.test.ts
types/caseData.d.ts

Ria 3144 appellant documents on docs tab

---

app/controllers/clarifying-questions/anything-else-answer.ts
app/controllers/clarifying-questions/check-and-send.ts
app/controllers/clarifying-questions/question-page.ts
app/controllers/clarifying-questions/supporting-evidence-question-page.ts
app/controllers/clarifying-questions/supporting-evidence.ts
app/controllers/reasons-for-appeal/check-and-send.ts
app/controllers/reasons-for-appeal/reason-for-appeal.ts
test/functional/features/reason-for-appeal.feature
test/unit/controllers/clarifying-questions/check-and-send.test.ts
test/unit/controllers/clarifying-questions/question-page.test.ts
test/unit/controllers/clarifying-questions/supporting-evidence-question-page.test.ts
test/unit/controllers/clarifying-questions/supporting-evidence.test.ts
test/unit/controllers/contact-details.test.ts
test/unit/controllers/reasons-for-appeal/check-and-send.test.ts
test/unit/controllers/reasons-for-appeal/reason-for-appeal.test.ts

https://tools.hmcts.net/jira/browse/RIA-3251
Refactoring submitEvent for:
- CQ CYA page
```
[ ] Yes
[ X ] No
```

RIA-3251: submitEvent refactored part iv

---

Dockerfile

Update node base image from alpine 10 to 12
```
[ ] Yes
[ x] No
```

Update node base image from alpine 10 to 12

---

app/data/events.ts
app/data/states.ts
app/service/update-appeal-service.ts
app/utils/application-state-utils.ts
app/utils/cma-hearing-details.ts
app/utils/date-utils.ts
app/utils/progress-bar-utils.ts
app/utils/timeline-utils.ts
locale/en.json
test/e2e-test/pages/common/common.ts
test/e2e-test/pages/sign-in.ts
test/functional/features/cma-requirements-listed.feature
test/functional/features/cma-requirements.feature
test/mock/ccd/mock-case-data/data/cmaListed.js
test/mock/ccd/mock-case-data/index.js
test/mock/ccd/mock-history-data/data/cma-listed.js
test/mock/ccd/mock-history-data/index.js
test/mock/ccd/services/loadCases.js
test/mock/ccd/services/loadHistoryV2.js
test/mock/ccd/services/otherEventStartEvent.js
test/mock/ccd/services/otherEventSubmitEvent.js
test/mock/idam/services/getDetails.js
test/mock/idam/services/getODetails.js
test/unit/mockData/mock-appeal.ts
test/unit/utils/application-state-utils.test.ts
test/unit/utils/event-deadline-date-finder.test.ts
test/unit/utils/task-utils.test.ts
types/caseData.d.ts
types/index.d.ts

https://tools.hmcts.net/jira/browse/RIA-3255
Added Cma Listed
```
[ ] Yes
[ x ] No
```

RIA-3255 Cma Listed

---

locale/en.json

https://tools.hmcts.net/jira/browse/RIA-2637
Improving alt-text on HO images.
```
[ ] Yes
[x ] No
```

RIA-2637: Improving alt texts

---

app/service/update-appeal-service.ts
types/caseData.d.ts

ria-3325-updated case-def

---

Jenkinsfile_nightly

Pause the nightly build
```
[ ] Yes
[ x] No
```

Pause the nightly build

---

Jenkinsfile_nightly

[RIA-3998](https://tools.hmcts.net/jira/browse/RIA-3998)
```
[ ] Yes
[x] No
```

RIA-3998 Fix nightly Jenkins build ia-aip-frontend

---

audit.json

[RIA-4075](https://tools.hmcts.net/jira/browse/RIA-4075)
This PR will be deleted once testing s complete. 
```
[ ] Yes
[x] No
```

Investigate security scan in build pipeline

---

audit.json

[RIA-4127](https://tools.hmcts.net/jira/browse/RIA-4127)
```
[ ] Yes
[x] No
```

RIA-4127 Fix OWASP warnings ia-aip-frontend

---

audit.json

[RIA-4127](https://tools.hmcts.net/jira/browse/RIA-4127)
```
[ ] Yes
[x] No
```

Ria 4127 a

---

audit.json

BAU Resolve OWASP warnings 
```
[ ] Yes
[x] No
```

BAU fix OWASP warnings in AIP

---

Dockerfile

[RIA-4202](https://tools.hmcts.net/jira/browse/RIA-4202)
```
[ ] Yes
[x] No
```

RIA-4202 Dockerfile Misconfiguration: Default User Privilege

---

app/utils/validations/fields-validations.ts
test/e2e-test/setup/reasons_for_appeal_requested.feature
test/functional/features/back-button.feature
test/functional/features/home-office-reference-page.feature
test/functional/features/out-of-time-appeal.feature
test/unit/controllers/home-office-details.test.ts
test/unit/utils/validations/fields-validations.test.ts

[RIA-4001](https://tools.hmcts.net/jira/browse/RIA-4001)
```
[ ] Yes
[x] No
```

RIA-4001 Home Office reference screens and validation

---

app/controllers/clarifying-questions/supporting-evidence-question-page.ts
app/controllers/clarifying-questions/supporting-evidence.ts

[RIA-4203](https://tools.hmcts.net/jira/browse/RIA-4203)
[CYBER-1511](https://tools.hmcts.net/jira/browse/CYBER-1511)
```
[ ] Yes
[x] No
```

RIA-4203 Open redirect

---

audit.json

BAU - Owasp fixes

---

test/e2e-test/features/basic.feature
test/unit/controllers/application-overview.test.ts
test/unit/controllers/reasons-for-appeal/reason-for-appeal.test.ts
test/unit/controllers/reasons-for-appeal/supporting-evidence-upload.test.ts
test/unit/controllers/reasons-for-appeal/supporting-evidence.test.ts
test/unit/utils/url-utils.test.ts

[RIA-4072](https://tools.hmcts.net/jira/browse/RIA-4072)
Investigate local tests 
```
[ ] Yes
[x] No
```

RIA-4072 investigate dev unit tests run

---

audit.json
yarn.lock

BAU fix red nightly build

---

locale/en.json
test/e2e-test/features/basic.feature
test/e2e-test/features/eligibility-questions.feature
test/e2e-test/setup/reasons_for_appeal_requested.feature
test/functional/features/eligibility-questions.feature

[RIA-4280](https://tools.hmcts.net/jira/browse/RIA-4280)
```
[ ] Yes
[x] No
```

RIA-4280 Eligibility questions - remove "are you at least 18 years old?"

---

locale/en.json
test/e2e-test/features/basic.feature
test/e2e-test/features/eligibility-questions.feature
test/e2e-test/setup/reasons_for_appeal_requested.feature
test/functional/features/eligibility-questions.feature

[RIA-4281](https://tools.hmcts.net/jira/browse/RIA-4281)
```
[ ] Yes
[x] No
```

RIA-4281 - Eligibility questions - remove "Immediate family appealing" question

---

locale/en.json
test/e2e-test/features/basic.feature
test/e2e-test/features/eligibility-questions.feature
test/e2e-test/setup/reasons_for_appeal_requested.feature
test/functional/features/eligibility-questions.feature

[RIA-4282](https://tools.hmcts.net/jira/browse/RIA-4282)
```
[ ] Yes
[x] No
```

RIA-4282 - Eligibility questions - update location question

---

app/controllers/eligibility.ts
locale/en.json
test/unit/controllers/eligibility.test.ts
views/eligibility/ineligible-page.njk

[RIA-4284](https://tools.hmcts.net/jira/browse/RIA-4284)
```
[ ] Yes
[x] No
```

RIA-4284 Eligibility questions - new ineligibility page for "Are you currently in detention?" page?

---

locale/en.json

[RIA-4289](https://tools.hmcts.net/jira/browse/RIA-4289)
Copy Change for eligibility question
```
[ ] Yes
[ x ] No
```

Copy change for eligibility question

---

views/eligibility/ineligible-page.njk

RIA-4283 ineligible h2 syntax

---

charts/ia-aip-frontend/Chart.yaml

[RIA-4313](https://tools.hmcts.net/jira/browse/RIA-4313)
```
[ ] Yes
[x] No
```

RIA-4313 Upgrade Charts dependency version for node.js

---

.gitignore
Jenkinsfile_nightly
package.json
stryker.node.conf.js
yarn.lock

[RIA-2333](https://tools.hmcts.net/jira/browse/RIA-2333)
```
[ ] Yes
[x] No
```

RIA-2333 - Add Mutation Testing

---

audit.json

BAU OWASP fix

---

test/e2e-test/pages/eligibility-questions/ineligible-page.ts

[RIA-4382](https://tools.hmcts.net/jira/browse/RIA-4382)
```
[ ] Yes
[x] No
```

RIA-4382 diagnose flaky test

---

yarn.lock

BAU - NPM fixes

---

yarn.lock

BAU minor package bump

---

app/service/update-appeal-service.ts
app/utils/tasks-utils.ts
test/functional/features/home-office-letter-sent-page.feature
test/unit/utils/task-utils.test.ts

Tasklist saved sections Hotfix 
```
[ ] Yes
[ x ] No
```

Hotfix tasklist saved sections

---

app/utils/application-state-utils.ts
app/utils/event-deadline-date-finder.ts
config/default.json
locale/en.json
test/e2e-test/pages/appeal-sent/appeal-sent.ts
test/functional/features/overview-page.feature
test/functional/features/submission-page.feature
test/unit/controllers/confirmation-page.test.ts
test/unit/utils/application-state-utils.test.ts
test/unit/utils/event-deadline-date-finder.test.ts
views/confirmation-page.njk

[RIA-4358](https://tools.hmcts.net/jira/browse/RIA-4358)
```
[ ] Yes
[x] No
```

RIA-4358 OOT Decisions: amends to Overview post-appeal form

---

locale/en.json
test/e2e-test/pages/ask-for-more-time/ask-for-more-time.ts
test/functional/features/ask-for-more-time.feature

[RIA-4384](https://tools.hmcts.net/jira/browse/RIA-4384)
```
[ ] Yes
[x] No
```

RIA-4384 RfMT before startingAppealReasons - confirmation page updates

---

app/controllers/detail-viewers.ts
app/service/ccd-service.ts
app/service/update-appeal-service.ts
locale/en.json
test/unit/controllers/detail-viewers.test.ts
test/unit/service/ccd-service.test.ts
types/index.d.ts

https://tools.hmcts.net/jira/browse/RIA-4316
Viewing HO decision letter
```
[ ] Yes
[ x ] No
```

RIA-4316: viewing ho letter

---

config/default.json
package.json
test/mock/postcode-lookup/services/postcodeLookup.js
yarn.lock

[RIA-4458](https://tools.hmcts.net/jira/browse/RIA-4458)
```
[ ] Yes
[x] No
```

RIA-4458 Post code look up service is not working in AIP

---

config/default.json

[RIA-4458](https://tools.hmcts.net/jira/browse/RIA-4458)
```
[ ] Yes
[x] No
```

RIA-4458 env vars

---

app/controllers/appeal-application/home-office-details-upload-decision-letter.ts
app/controllers/appeal-application/out-of-time.ts
app/controllers/clarifying-questions/anything-else-question.ts
app/controllers/clarifying-questions/supporting-evidence-question-page.ts
app/controllers/clarifying-questions/supporting-evidence.ts
app/controllers/reasons-for-appeal/reason-for-appeal.ts
app/controllers/upload-evidence/upload-evidence-controller.ts
app/service/document-management-service.ts
app/service/update-appeal-service.ts
test/e2e-test/pages/common/common.ts
test/e2e-test/pages/common/file-upload-common.ts
test/functional/features/0-submit-appeal.feature
test/mock/idam/services/getODetails.js
test/unit/controllers/clarifying-questions/supporting-evidence.test.ts
test/unit/controllers/out-of-time.test.ts
test/unit/service/document-management-service.test.ts
test/unit/service/update-appeal-service.test.ts
views/appeal-application/personal-details/nationality.njk
views/templates/multiple-evidence-upload-page.njk

https://tools.hmcts.net/jira/browse/RIA-4375
Unabel delete file Bug fix
```
[ ] Yes
[ x ] No
```

RIA-4375: Unable delete file

---

Jenkinsfile_nightly

[RIA-4398](https://tools.hmcts.net/jira/browse/RIA-4398)
enable functional tests in nightly build
```
[ ] Yes
[x] No
```

enable functional tests in nightly build

---

Jenkinsfile_nightly

N/A
fix Jenkins build
```
[ ] Yes
[x] No
```

fix Jenkins build

---

package.json

N/A
fix typo in Jenkins build config
```
[ ] Yes
[x] No
```

fix typo in Jenkins build config

---

app/assets/scss/application.scss
app/controllers/application-overview.ts
app/service/update-appeal-service.ts
app/setupSecrets.ts
app/utils/application-state-utils.ts
app/utils/cma-hearing-details.ts
charts/ia-aip-frontend/Chart.yaml
charts/ia-aip-frontend/values.yaml
config/custom-environment-variables.json
config/default.json
locale/en.json
test/functional/features/end-of-appeal.feature
test/unit/controllers/application-overview.test.ts
test/unit/service/update-appeal-service.test.ts
test/unit/utils/application-state-utils.test.ts
test/unit/utils/event-deadline-date-finder.test.ts
types/caseData.d.ts
types/index.d.ts
views/application-overview.njk

[RIA-4323](https://tools.hmcts.net/jira/browse/RIA-4323)
```
[ ] Yes
[x] No
```

RIA-4323 End Appeal: timeline updates

---

app/controllers/appeal-application/check-and-send.ts
app/controllers/appeal-application/personal-details.ts
app/service/update-appeal-service.ts
app/utils/validations/fields-validations.ts
client/__tests__/nationality-utils.test.ts
client/nationality-utils.ts
client/utils.ts
package.json
test/functional/features/overview-page.feature
test/unit/controllers/nationatily-page.test.ts
test/unit/extensions/mobile-number.test.ts
types/caseData.d.ts
types/index.d.ts
views/appeal-application/personal-details/nationality.njk
yarn.lock

https://tools.hmcts.net/jira/browse/RIA-4297
Adding stateless option to nationality question
```
[ ] Yes
[ x ] No
```

RIA-4297: Adding stateless option to nationality question

---

app/controllers/footer.ts
app/paths.ts
locale/en.json
test/unit/controllers/footer.test.ts
views/footer/accessibility-statement.njk
views/layout.njk

https://tools.hmcts.net/jira/browse/RIA-4394
New accessibility statement page
```
[ ] Yes
[ x ] No
```

RIA-4394: Accessibility page

---

app/utils/application-state-utils.ts
locale/en.json
test/e2e-test/pages/overview-page/overview-page.ts
test/unit/utils/application-state-utils.test.ts

[RIA-4360](https://tools.hmcts.net/jira/browse/RIA-4360)
```
[ ] Yes
[x] No
```

RIA-4360 OOT Decisions: amends to Summary page for appeal cannot continue decision

---

app/controllers/detail-viewers.ts

Stateless copy on appeal viewer fix
```
[ ] Yes
[ x ] No
```

HotFix: stateless appeal viewer fix

---

app/data/states.ts
app/service/update-appeal-service.ts
app/utils/application-state-utils.ts
locale/en.json
test/unit/utils/application-state-utils.test.ts
types/caseData.d.ts
types/index.d.ts
views/application-overview.njk

https://tools.hmcts.net/jira/browse/RIA-4546
Added overview page content for appeal moved offline.
```
[ ] Yes
[X] No
```

RIA-4546: Added overview page content for appeal moved offline.

---

test/e2e-test/features/eligibility-questions.feature
test/e2e-test/features/smoke.feature
test/e2e-test/pages/common/common.ts

RIA-4647
Smoke Test
```
[ ] Yes
[x] No
```

Smoke Test

---

app/app-config.ts
app/controllers/appeal-application/confirmation-page.ts
app/controllers/detail-viewers.ts
app/service/s2s-service.ts
app/utils/application-state-utils.ts
app/utils/timeline-utils.ts
locale/en.json
package.json
test/unit/controllers/application-overview.test.ts
test/unit/controllers/detail-viewers.test.ts
test/unit/utils/event-deadline-date-finder.test.ts
test/unit/utils/timeline-utils.test.ts
test/utils/common.ts
views/detail-viewers/time-extension-details-viewer.njk
yarn.lock

https://tools.hmcts.net/jira/browse/RIA-4386
```
[ ] Yes
[ x ] No
```

Ria 4386 rmft viewer

---

views/application-overview.njk

HotFix: Ask for more time link on overview page not working
```
[ ] Yes
[ x ] No
```

HotFix: afmt link

---

test/functional/features/clarifying-questions.feature
views/upload-evidence/supporting-evidence-upload-page.njk

https://tools.hmcts.net/jira/browse/RIA-4391
Request for more time during Clarifying Questions flow
```
[ ] Yes
[ x ] No
```

RIA-4391: Request for more time during CQ

---

app/controllers/reasons-for-appeal/reason-for-appeal.ts

https://tools.hmcts.net/jira/browse/RIA-4565
Fix date format issue
```
[ ] Yes
[ x ] No
```

date format fix

---

Jenkinsfile_CNP
config/development.json
test/e2e-test/features/basic.feature
test/e2e-test/pages/home-office-details/home-office-letter-sent.ts

[RIA-4398](https://tools.hmcts.net/jira/browse/RIA-4398)
```
[ ] Yes
[x] No
```

RIA-4398 AiP Automated Testing - Functional tests

---

Jenkinsfile_nightly
charts/ia-aip-frontend/Chart.yaml
config/development.json

Bau red nightly ci 020821

---

app/app.ts
app/assets/scss/_cookie-banner.scss
app/assets/scss/_save-buttons-component.scss
client/cookies-banner.ts
locale/en.json
test/e2e-test/pages/common/common.ts
test/functional/features/cookies.feature
test/unit/client/cookies-banner.test.ts
types/window.d.ts
views/layout.njk

https://tools.hmcts.net/jira/browse/RIA-4687
Analytics cookie consent
```
[ ] Yes
[ x ] No
```

RIA-4687: Analytics cookie consent

---

client/cookies-banner.ts

Adding cookies_policy cookie
```
[ ] Yes
[ X ] No
```

HotFix: Adding cookies_policy cookie

---

client/cookies-banner.ts

Initialize cookies_policy to false before consent has given/rejected
```
[ ] Yes
[ x ] No
```

HotFix: Adding cookies_policy cookie initialization

---

client/cookies-banner.ts

Dyna trace cookies management
```
[ ] Yes
[ x ] No
```

Hotfix: Dyna cookies management

---

client/cookies-banner.ts
sonar-project.properties

Cookies remove from all domains
```
[ ] Yes
[ x ] No
```

Hotfix: cookies remove all domains

---

client/cookies-banner.ts

N/A
Dynatrace trigger re-ordering
```
[ ] Yes
[x] No
```

Dynatrace trigger re-ordering

---

client/cookies-banner.ts

Disabling dyna first
```
[ ] Yes
[ x ] No
```

Hotfix: disabling dyna first

---

locale/en.json

Cookies page copy update
```
[ ] Yes
[ x ] No
```

Cookies page copy

---

app/assets/scss/_save-buttons-component.scss

Button miss alignment fix
```
[ ] Yes
[ x ] No
```

Fixing save buttons alignment

---

app/controllers/guidance-page.ts
app/paths.ts
app/utils/guidance-page-utils.ts
locale/en.json
test/unit/controllers/guidance-page.test.ts
test/unit/utils/application-state-utils.test.ts
views/guidance-pages/guidance-page.njk

[RIA-4672](https://tools.hmcts.net/jira/browse/RIA-4672)
```
[ ] Yes
[x] No
```

RIA-4672 Appellant Timeline page -What to expect at a hearing guidance page

---

app/controllers/guidance-page.ts
app/paths.ts
app/utils/guidance-page-utils.ts
locale/en.json
test/unit/controllers/guidance-page.test.ts
test/unit/utils/application-state-utils.test.ts
views/guidance-pages/guidance-page.njk

Reverts hmcts/ia-aip-frontend#553

Revert "RIA-4672 Appellant Timeline page -What to expect at a hearing guidance page"

---

sonar-project.properties

N/A
Sonar property fix
```
[ ] Yes
[x] No
```

Sonar property fix

---

app/controllers/guidance-page.ts
app/paths.ts
app/utils/guidance-page-utils.ts
locale/en.json
test/unit/controllers/guidance-page.test.ts
test/unit/utils/application-state-utils.test.ts
views/guidance-pages/guidance-page.njk

Reverts hmcts/ia-aip-frontend#557

Revert "Revert "RIA-4672 Appellant Timeline page -What to expect at a hearing guidance page""

---

app/assets/scss/application.scss
locale/en.json
test/unit/utils/application-state-utils.test.ts

https://tools.hmcts.net/jira/browse/RIA-4614
overview banner color change
```
[ ] Yes
[  x] No
```

updated overview banner color scheme

---

app/assets/scss/application.scss
app/controllers/application-overview.ts
app/controllers/ask-for-more-time/ask-for-more-time.ts
app/controllers/clarifying-questions/anything-else-answer.ts
app/controllers/clarifying-questions/question-page.ts
app/controllers/clarifying-questions/supporting-evidence-question-page.ts
app/controllers/clarifying-questions/supporting-evidence.ts
app/controllers/detail-viewers.ts
app/utils/application-state-utils.ts
app/utils/event-deadline-date-finder.ts
locale/en.json
test/functional/features/clarifying-questions.feature
test/unit/controllers/application-overview.test.ts
test/unit/controllers/ask-for-more-time.test.ts
test/unit/controllers/clarifying-questions/question-page.test.ts
test/unit/utils/application-state-utils.test.ts
types/index.d.ts
views/application-overview.njk
views/ask-for-more-time/confirmation.njk
views/clarifying-questions/question-page.njk
views/templates/textarea-question-page.njk
views/upload-evidence/supporting-evidence-question-page.njk
views/upload-evidence/supporting-evidence-upload-page.njk

https://tools.hmcts.net/jira/browse/RIA-4392
Requests for more time during CQ timeline
```
[ ] Yes
[ x ] No
```

Ria 4392: rfmt during cq

---

app/data/events.ts
app/utils/timeline-utils.ts
locale/en.json

https://tools.hmcts.net/jira/browse/RIA-4745
Timeline update
```
[ ] Yes
[ x ] No
```

RIA-4745: Timeline update

---

app/api/payments-api.ts
app/controllers/appeal-application/check-and-send.ts
app/controllers/appeal-application/type-of-appeal.ts
app/paths.ts
app/routes.ts
app/service/payments-service.ts
app/service/update-appeal-service.ts
config/custom-environment-variables.json
config/development.json
config/test.json
test/unit/api/payments-api.test.ts
test/unit/controllers/check-and-send.test.ts
test/unit/service/ccd-service.test.ts
test/unit/service/payments-service.test.ts
types/caseData.d.ts
types/index.d.ts

https://tools.hmcts.net/jira/browse/RIA-4803
```
[ ] Yes
[x] No
```

Ria 4803 AiP Payments service integration

---

test/e2e-test/features/basic.feature

replaced  @crossbrowse with @crossbrowser in basic.feature for e2e
```
[ ] Yes
[X] No
```

changed @crossbrowse to @crossbrowser

---

app/controllers/detail-viewers.ts
app/data/events.ts
app/paths.ts
app/utils/timeline-utils.ts
locale/en.json
test/unit/controllers/detail-viewers.test.ts
test/unit/utils/timeline-utils.test.ts

https://tools.hmcts.net/jira/browse/RIA-4660
New screens for DC and RP, fees confirmation (front end)
```
[ ] Yes
[X] No
```

RIA-4660 HO Response: HO decision - Appellant completed action changes

---

package.json
test/e2e-test/features/basic.feature
test/e2e-test/service/idam-service.ts

https://tools.hmcts.net/jira/browse/RIA-4882
Run `yarn codecept:e2e-local -g @e2e` to run test on local environment
```
[ ] Yes
[X] No
```

RIA-4882 Function Test updates following new HO feature flag

---

views/application-overview.njk

https://tools.hmcts.net/jira/browse/RIA-4707
```
[ ] Yes
[ x ] No
```

RIA-4707 hotfix

---

charts/ia-aip-frontend/Chart.yaml
charts/ia-aip-frontend/values.yaml

N/A
Fix for payments url as part of SIT.
```
[ ] Yes
[x] No
```

Fix for incorrect payments url

---

app/api/payments-api.ts

N/A
Fix for service-callback URL (part of SIT testing)
```
[ ] Yes
[x] No
```

Fix for payment-update endpoint url

---

app/service/payments-service.ts

Payment request update to pass correct values for AIP card payment

---

app/service/launchDarkly-service.ts

RIA-5150: clean up log statement

---

app/service/launchDarkly-service.ts

Reverts hmcts/ia-aip-frontend#648

Revert "RIA-5150: clean up log statement"

---

test/e2e-test/features/basic.feature

https://tools.hmcts.net/jira/browse/RIA-5149
Card payment: e2e Tests eligibility flow
```
[ ] Yes
[X] No
```

RIA-5149 bypass e2e eligibility

---

test/e2e-test/features/basic.feature

N/A
Commenting out problematic LD steps
```
[ ] Yes
[x] No
```

Comment e2e steps

---

audit.json

BAU Fix nightly Jenkins build ia-aip-frontend

---

Jenkinsfile_CNP
Jenkinsfile_nightly
app/controllers/appeal-application/pay-now.ts
app/controllers/pcq.ts
app/createToken.ts
app/data/constants.ts
charts/ia-aip-frontend/Chart.yaml
charts/ia-aip-frontend/values.aat.template.yaml
charts/ia-aip-frontend/values.preview.template.yaml
charts/ia-aip-frontend/values.yaml
config/custom-environment-variables.json
config/default.json
test/unit/controllers/pcq.test.ts

[RIA-5128](https://tools.hmcts.net/jira/browse/RIA-5128)
```
[ ] Yes
[x] No
```

RIA-5128 AIP PCQ start point for PA cases (rebased)

---

app/controllers/appeal-application/decision-type.ts
app/setupSecrets.ts
charts/ia-aip-frontend/Chart.yaml
test/unit/controllers/decision-type.test.ts

[RIA-5129](https://tools.hmcts.net/jira/browse/RIA-5129)
```
[ ] Yes
[x] No
```

RIA-5129 AIP PCQ start point for EEA, HR, DOC, RP case types (rebased)

---

charts/ia-aip-frontend/Chart.yaml
charts/ia-aip-frontend/values.yaml

[RIA-5128](https://tools.hmcts.net/jira/browse/RIA-5128)
```
[ ] Yes
[x] No
```

RIA-5128 PCQ_URL Yaml

---

app/controllers/appeal-application/confirmation-page.ts
app/service/payments-service.ts
charts/ia-aip-frontend/Chart.yaml
charts/ia-aip-frontend/values.yaml

BAU additional payment logging

---

app/controllers/hearing-requirements/check-and-send.ts
test/unit/controllers/hearing-requirements/check-and-send.test.ts

add log statement for hearing requirements successful submisson
```
[ ] Yes
[ ] No
```

add log statement for hearing requirements

---

app/controllers/appeal-application/confirmation-page.ts
app/service/pcq-service.ts

BAU additional logging for PCQ

---

app/controllers/application-overview.ts
app/controllers/detail-viewers.ts
app/controllers/hearing-requirements/hearings-feature-toggle.ts
app/controllers/out-of-country/ooc-feature-toggle.ts
app/data/constants.ts
app/data/events.ts
app/middleware/hearing-requirements-middleware.ts
app/middleware/outofcountry-feature-middleware.ts
app/paths.ts
app/routes.ts
app/service/update-appeal-service.ts
app/utils/application-state-utils.ts
app/utils/cma-hearing-details.ts
app/utils/progress-bar-utils.ts
app/utils/timeline-utils.ts
locale/en.json
test/unit/controllers/detail-viewers.test.ts
test/unit/controllers/hearing-requirements/hearings-feature-toggle.test.ts
test/unit/controllers/out-of-country/ooc-feature-toggle.test.ts
test/unit/middleware/hearing-requirements-middleware.test.ts
test/unit/middleware/outofcountry-feature-middleware.test.ts
test/unit/utils/application-state-utils.test.ts
test/unit/utils/progress-bar.test.ts
types/caseData.d.ts
types/index.d.ts

RIA-4860 List case: Appellant time line update 'Complete actions'

---

app/controllers/application-overview.ts
app/controllers/detail-viewers.ts
app/controllers/guidance-page.ts
app/paths.ts
app/service/update-appeal-service.ts
app/utils/application-state-utils.ts
app/utils/guidance-page-utils.ts
app/utils/progress-bar-utils.ts
locale/en.json
test/unit/controllers/application-overview.test.ts
test/unit/controllers/detail-viewers.test.ts
test/unit/controllers/guidance-page.test.ts
test/unit/service/update-appeal-service.test.ts
test/unit/utils/application-state-utils.test.ts
types/caseData.d.ts
types/index.d.ts

[RIA-4930](https://tools.hmcts.net/jira/browse/RIA-4930)
```
[ ] Yes
[x] No
```

RIA-4930 Final Bundle: Appellant Timeline page - Update to 'Next action'

---

app/controllers/guidance-page.ts
app/data/events.ts
app/service/ccd-service.ts
app/utils/timeline-utils.ts
locale/en.json
test/unit/controllers/detail-viewers.test.ts
test/unit/controllers/guidance-page.test.ts
test/unit/utils/application-state-utils.test.ts

RIA-4931: Final Bundling - Appellant completed action changes (UI Changes)

---

app/controllers/application-overview.ts
test/unit/controllers/application-overview.test.ts

BAU getHearingDetails date time hotfix

---

app/controllers/detail-viewers.ts
app/controllers/hearing-requirements/hearings-feature-toggle.ts
app/paths.ts
app/service/update-appeal-service.ts
app/utils/application-state-utils.ts
app/utils/event-deadline-date-finder.ts
locale/en.json
test/unit/controllers/detail-viewers.test.ts
test/unit/service/update-appeal-service.test.ts
test/unit/utils/application-state-utils.test.ts
types/caseData.d.ts
types/index.d.ts
views/templates/details-viewer.njk

[RIA-4933](url)
add what to do next option

RIA-4933:  add what to do next option

---

app/data/events.ts
app/utils/timeline-utils.ts
locale/en.json
views/components/overview-timeline.njk

[RIA-4935](https://tools.hmcts.net/jira/browse/RIA-4935)
```
[ ] Yes
[x] No
```

RIA-4935 Decision: Appellant Timeline page - Completed actions update and 'Decision and reasons'

---

app/controllers/upload-evidence/provide-more-evidence-controller.ts
app/paths.ts
app/service/update-appeal-service.ts
app/utils/timeline-utils.ts
locale/en.json
test/e2e-test/features/basic.feature
test/unit/controllers/provide-more-evidence-controller.test.ts
test/unit/service/update-appeal-service.test.ts
types/index.d.ts

[RIA-4698](https://tools.hmcts.net/jira/browse/RIA-4698)
```
[ ] Yes
[x] No
```

RIA-4698 AiP provide more evidence - Appellants Completed actions changes - pre-bundling

---

app/controllers/eligibility.ts
locale/en.json
test/e2e-test/features/basic.feature
test/e2e-test/features/eligibility-questions.feature
test/e2e-test/setup/reasons_for_appeal_requested.feature
test/functional/features/eligibility-questions.feature
test/unit/controllers/eligibility.test.ts

[RIA-4966](https://tools.hmcts.net/jira/browse/RIA-4966)
```
[ ] Yes
[x] No
```

RIA-4966 Updated Eligibility questions to allow for OOC

---

client/cookies-banner.ts
locale/en.json
test/unit/client/cookies-banner.test.ts

RIA-4974 Initial commit

---

locale/en.json
test/unit/utils/application-state-utils.test.ts

https://tools.hmcts.net/jira/browse/RIA-5470
https://tools.hmcts.net/jira/browse/RIA-5465
Added full stop and fixed typo on relevant screens.
```
[ ] Yes
[x] No
```

fixes made

---

app/utils/tasks-utils.ts

added homeOfficeDetailsOOC to task utils

---

app/utils/tasks-utils.ts

 personal details fix

---

client/cookies-banner.ts

https://tools.hmcts.net/jira/browse/RIA-4974
Disable dynatrace based on Cookies preference
```
[ ] Yes
[x ] No
```

RIA-4794:Disable dynatrace based on Cookies selection

---

app/controllers/make-application/hearing-requests/hearing-application-type.ts
app/data/application-types.ts
app/middleware/journeyAllowed-middleware.ts
app/paths.ts
app/routes.ts
locale/en.json
test/unit/controllers/make-application/hearing-requests/hearing-application-type.test.ts
types/index.d.ts
views/make-application/application-type-page.njk

https://tools.hmcts.net/jira/browse/RIA-5821
```
[ ] Yes
[x] No
```

RIA-5821: Implement 'Ask to change something about your hearing' page

---

app/controllers/make-application/hearing-requests/adjourn-hearing-application.ts
app/controllers/make-application/hearing-requests/setup-hearing-application-controllers.ts
app/paths.ts
locale/en.json
test/functional/features/adjourn-hearing-application.feature
test/unit/controllers/make-application/hearing-requests/adjourn-hearing-application.test.ts
test/unit/controllers/make-application/hearing-requests/setup-hearing-application-controllers.test.ts

https://tools.hmcts.net/jira/browse/RIA-5823
Make Application - Appellant make hearing orientated application: 'Ask for the hearing to be later' application process
```
[ ] Yes
[x] No
```

RIA-5823 Make Application: Ask for the hearing to be later

---

views/make-application/details-question-page.njk
views/make-application/radio-button-question-page.njk

RIA-5821: Fix typo in template

---

app/controllers/make-application/make-application-common.ts
app/controllers/make-application/make-application-controllers-helper.ts
test/unit/controllers/make-application/make-application-controllers-helper.test.ts

https://tools.hmcts.net/jira/browse/RIA-5823
```
[ ] Yes
[x] No
```

RIA-5823: Include link to change answer to question on CYA page

---

app/controllers/make-application/appeal-requests/link-or-unlink-appeal-application.ts
app/controllers/make-application/appeal-requests/setup-appeal-application-controllers.ts
app/controllers/make-application/hearing-requests/setup-hearing-application-controllers.ts
app/paths.ts
locale/en.json
test/e2e-test/pages/make-application/make-appeal-application.ts
test/functional/features/link-or-unlink-appeal-application.feature
test/unit/controllers/make-application/appeal-requests/link-or-unlink-appeal-application.test.ts
test/unit/controllers/make-application/appeal-requests/setup-appeal-application-controllers.test.ts
views/application-overview.njk

https://tools.hmcts.net/jira/browse/RIA-5828
```
[ ] Yes
[x] No
```

RIA-5828: Make Application 'Ask to link or unlink with another appeal'

---

locale/en.json

https://tools.hmcts.net/jira/browse/RIA-5826
Fixed type in question description
```
[ ] Yes
[x] No
```

RIA-5826 Fixed typo in question description

---

app/controllers/application-overview.ts
app/data/constants.ts
test/unit/controllers/application-overview.test.ts
views/application-overview.njk

https://tools.hmcts.net/jira/browse/RIA-6005
```
[ ] Yes
[x] No
```

RIA-6005: Add Launch Darkly feature flag for Make an Application

---

charts/ia-aip-frontend/Chart.yaml
charts/ia-aip-frontend/values.yaml

RIA-5886 fix redis chart version

---

charts/ia-aip-frontend/Chart.yaml
charts/ia-aip-frontend/values.preview.template.yaml
charts/ia-aip-frontend/values.yaml

To fix master build failure
To fix master build failure
```
[ ] Yes
[X ] No
```

Updates to fix master build failures

---

charts/ia-aip-frontend/values.aat.template.yaml

Updates to fix redis url for aat
Updates to fix redis url for aat
```
[ ] Yes
[X ] No
```

Updates to fix redis url version in aat

---

charts/ia-aip-frontend/Chart.yaml
charts/ia-aip-frontend/values.aat.template.yaml

This is to fix deployment failure in aat
This is to fix deployment failure in aat
```
[ ] Yes
[X ] No
```

Fix master build failure aat

---

views/change-representation.njk

https://tools.hmcts.net/jira/browse/RIA-5963
RIA-5963 Appellant accesses guidance on what to do if they stop representing themselves
* added missing colon in view.
```
[ ] Yes
[X] No
```

RIA-5963 Appellant accesses guidance on what to do if they stop representing themselves

---

app/controllers/appeal-application/check-and-send.ts
app/controllers/detail-viewers.ts
locale/en.json

[RIA-5587](https://tools.hmcts.net/jira/browse/RIA-5587)
- Removed obsolete EU Settlement Scheme screen
- Added new type EU Settlement Scheme to choose from
```
[ ] Yes
[x] No
```

RIA-5587 Add EU appeal type

---

app/controllers/detail-viewers.ts
test/unit/controllers/detail-viewers.test.ts

https://tools.hmcts.net/jira/browse/RIA-6049
Removed duplicate Home Office Number from appeal details view.
```
[ ] Yes
[X] No
```

RIA-6049 Appellant views appeal details

---

app/controllers/detail-viewers.ts
app/data/events.ts
app/paths.ts
app/service/ccd-service.ts
app/utils/application-state-utils.ts
app/utils/event-deadline-date-finder.ts
app/utils/progress-bar-utils.ts
app/utils/timeline-utils.ts
locale/en.json
test/unit/controllers/detail-viewers.test.ts
test/unit/utils/event-deadline-date-finder.test.ts
test/unit/utils/progress-bar.test.ts
test/unit/utils/timeline-utils.test.ts
views/detail-viewers/reasons-for-appeal-details-viewer.njk

https://tools.hmcts.net/jira/browse/RIA-6050
```
[ ] Yes
[x] No
```

RIA-6050: Appellant views Skeleton Argument/Evidence

---

app/data/events.ts
app/utils/application-state-utils.ts
app/utils/timeline-utils.ts
locale/en.json
test/unit/utils/application-state-utils.test.ts
test/unit/utils/timeline-utils.test.ts

https://tools.hmcts.net/jira/browse/RIA-6054
```
[ ] Yes
[x] No
```

RIA-6054: Appellant views hearing bundle

---

app/controllers/hearing-requirements/hearing-requirements-summary-sections.ts
app/paths.ts
app/service/update-appeal-service.ts
locale/en.json
test/unit/controllers/hearing-requirements/your-hearing-needs.test.ts
types/caseData.d.ts
types/index.d.ts

https://tools.hmcts.net/jira/browse/RIA-6051
Added Appellant and Appeal Oral Evidence sections under Witnesses.
Renamed Witnesses section to Attendance but only if above flags are set. This is to allow the existing check your answers page to exist as it currently does without these too questions.
```
[ ] Yes
[x ] No
```

RIA-6051 Appellant views hearing requirements

---

app/controllers/start-represent-yourself.ts
locale/en.json
test/functional/features/start-representing-yourself.feature
test/unit/controllers/start-representing-yourself.test.ts

https://tools.hmcts.net/jira/browse/RIA-6045
https://tools.hmcts.net/jira/browse/RIA-6046
Fixes for issues found in QA
- Display previously entered case reference number when there is an error or using the back button
- Updated error messages
- After case confirmed redirect to IDAM register page
```
[ ] Yes
[X] No
```

RIA-6046 Fixes for issues found in QA

---

app/controllers/hearing-requirements/hearing-requirements-summary-sections.ts
test/unit/controllers/hearing-requirements/your-hearing-needs.test.ts

https://tools.hmcts.net/jira/browse/RIA-6051
Added in undefined check 
```
[ ] Yes
[X] No
```

RIA-6051: View hearing requirements with appellant specific information - undefined check

---

app/service/update-appeal-service.ts
test/unit/service/update-appeal-service.test.ts

https://tools.hmcts.net/jira/browse/RIA-6357
Multimedia Evidence Changes for AIP/LR when AIP takes over case
```
[ ] Yes
[X] No
```

RIA-6357 Multimedia Evidence Changes for AIP/LR when AIP takes over case

---

test/e2e-test/features/AiP-to-LR-NoC.feature
test/e2e-test/features/failed-payments.feature
test/e2e-test/features/full-e2e.feature
test/e2e-test/features/legal-rep-to-aip-noc.feature
test/e2e-test/features/make-an-application.feature
test/e2e-test/pages/check-and-send/check-and-send.ts
test/e2e-test/pages/make-application/make-appeal-application.ts
test/e2e-test/pages/start-representing-yourself/start-representing-yourself.ts

fixes to current nightly build tests

---

app/service/payments-service.ts

[RIA-6574](https://tools.hmcts.net/jira/browse/RIA-6574)
- Added HMCTS case reference number (e.g. HU/50001/2023) to data being sent with the payment
```
[ ] Yes
[x] No
```

RIA-6574 Add reference number to info passed with payments

---

app/controllers/application-overview.ts
test/unit/controllers/application-overview.test.ts

https://tools.hmcts.net/jira/browse/RIA-6971
```
[ ] Yes
[x] No
```

RIA-6971: Update timeline content post-decision

---

app/controllers/detail-viewers.ts
app/data/constants.ts
app/data/events.ts
app/paths.ts
app/service/update-appeal-service.ts
app/utils/application-state-utils.ts
app/utils/timeline-utils.ts
app/utils/utils.ts
locale/en.json
test/unit/controllers/detail-viewers.test.ts
test/unit/utils/application-state-utils.test.ts
test/unit/utils/timeline-utils.test.ts
types/caseData.d.ts
types/index.d.ts
views/ftpa-application/ftpa-decision-details-viewer.njk

https://tools.hmcts.net/jira/browse/RIA-6904
* Updates to application overview 'Do this next' section after respondent ftpa application is decided
* Updates to the application overview time line after respondent ftpa application is decided
* Created details page for respondent ftpa application/decision details
* Created new unit tests and updated existing ones based on the new updates.
```
[ ] Yes
[x] No
```

RIA-6904: Appellant's view when a Judge makes decision on FTPA - HO

---

app/controllers/detail-viewers.ts
app/paths.ts
app/service/update-appeal-service.ts
app/utils/application-state-utils.ts
locale/en.json
test/unit/controllers/detail-viewers.test.ts
test/unit/utils/application-state-utils.test.ts
types/caseData.d.ts
types/index.d.ts

https://tools.hmcts.net/jira/browse/RIA-7037
```
[ ] Yes
[x] No
```

Appellant's view when a Judge makes decision on FTPA - Completed Section

---

app/controllers/application-overview.ts
app/controllers/ftpa/ftpa-application.ts
locale/en.json
test/unit/controllers/application-overview.test.ts
test/unit/controllers/ftpa-applications.test.ts
views/application-overview.njk

https://tools.hmcts.net/jira/browse/RIA-7058
* Add a link to apply for FTPA in the overview's side menu
* This link is only available after a decision on the appeal (in post decision states)
* Clear local user-supplied FTPA related data at the start of a new FTPA application
```
[ ] Yes
[x] No
```

RIA-7058 Enable FTPA Application in FTPA Submitted & Decided state for Appellant

---

app/service/ccd-service.ts
app/service/update-appeal-service.ts
test/unit/service/ccd-service.test.ts
types/ccd.d.ts

[RIA-6516](https://tools.hmcts.net/jira/browse/RIA-6516)
- Copy of PR originally opened on master to handle ccd supplementary data in aip
```
[ ] Yes
[x] No
```

RIA-6516 Copy of PR for supplementary data

---

app/service/update-appeal-service.ts
types/caseData.d.ts

https://tools.hmcts.net/jira/browse/RIA-7037
```
[ ] Yes
[x] No
```

RIA-7037: Fix issue with missing late FTPA application documents

---

app/controllers/detail-viewers.ts
app/paths.ts
app/utils/timeline-utils.ts
locale/en.json
test/unit/controllers/detail-viewers.test.ts

https://tools.hmcts.net/jira/browse/RIA-6999
-Add the new page for viewing sendDirection detail
-Add the Unit test
```
[ ] Yes
[X] No
```

RIA-6999 Tribunal sends Non Standard Direction to the Appellant/HO - New Details Page

---

views/detail-viewers/direction-history-viewer.njk

https://tools.hmcts.net/jira/browse/RIA-6999
-Add the page of direction-history-view.njk for viewing the detail of sending direction
```
[ ] Yes
[X] No
```

RIA-6999 Tribunal send NSD to appellant ho detail page v2

---

app/utils/cma-hearing-details.ts
locale/en.json
test/unit/controllers/detail-viewers.test.ts

https://tools.hmcts.net/jira/browse/RIA-6959
```
[ ] Yes
[x] No
```

RIA-6959 Fix issues with application types and hearing centre emails

---

app/controllers/detail-viewers.ts
app/utils/application-state-utils.ts
app/utils/timeline-utils.ts
locale/en.json
test/mock/ccd/mock-case-data/data/decided-es.js
test/mock/ccd/mock-case-data/data/decided.js
test/mock/ccd/mock-case-data/data/ftpa-out-of-time-application-started-es.js
test/mock/ccd/mock-case-data/data/ftpa-out-of-time-application-started.js
test/mock/ccd/services/otherEventStartEvent.js
test/mock/ccd/services/otherEventSubmitEvent.js
test/unit/controllers/detail-viewers.test.ts
test/unit/utils/application-state-utils.test.ts
test/unit/utils/timeline-utils.test.ts
views/detail-viewers/make-an-application-details-viewer.njk

https://tools.hmcts.net/jira/browse/RIA-7145
```
[ ] Yes
[x] No
```

RIA-7145: Appellant's view when HO Application has been decided

---

app/utils/application-state-utils.ts
app/utils/timeline-utils.ts
locale/en.json
test/unit/utils/application-state-utils.test.ts
test/unit/utils/timeline-utils.test.ts

https://tools.hmcts.net/jira/browse/RIA-7151
```
[ ] Yes
[x] No
```

RIA-7151 Appellant's View when Home Office makes an FTPA Application

---

app/controllers/detail-viewers.ts
app/utils/application-state-utils.ts
app/utils/timeline-utils.ts
app/utils/utils.ts
test/mock/ccd/mock-case-data/data/decided-es.js
test/mock/ccd/mock-case-data/data/decided.js
test/mock/ccd/mock-case-data/data/ftpa-out-of-time-application-started-es.js
test/mock/ccd/mock-case-data/data/ftpa-out-of-time-application-started.js
test/unit/utils/application-state-utils.test.ts
test/unit/utils/utils.test.ts

https://tools.hmcts.net/jira/browse/RIA-7151
```
[ ] Yes
[x] No
```

RIA-7151 Appellant's View when Home Office makes an FTPA Application (issues fixes)

---

app/data/events.ts
app/utils/application-state-utils.ts
locale/en.json
test/unit/utils/application-state-utils.test.ts

https://tools.hmcts.net/jira/browse/RIA-6248
```
[ ] Yes
[x] No
```

RIA-6248: Update to Appellant's Timeline Page when LO triggers DWH event

---

locale/en.json

https://tools.hmcts.net/jira/browse/RIA-7056
* Content changes
```
[ ] Yes
[X] No
```

RIA-7056 content changes

---

locale/en.json

https://tools.hmcts.net/jira/browse/RIA-7056
* Separating 2 pieces of text with a new line
```
[ ] Yes
[X] No
```

RIA-7056 Added new line to seperate 2 pieces of text

---

infrastructure/main.tf

Changed redis cache subnet name

Redis cache name change

---

config/default.json
infrastructure/main.tf

Retrying to update the redis cache

Redis upgrade (again)

---

infrastructure/main.tf

Removing redis from terraform in attempt to restore master build

Removing redis from terraform config

---

app/setupSecrets.ts
charts/ia-aip-frontend/Chart.yaml
charts/ia-aip-frontend/values.yaml

Removing redis secrets

---

infrastructure/main.tf

Allows deletion of Redis cache from prod

Allowing deletion of cache

---

app/setupSecrets.ts
charts/ia-aip-frontend/Chart.yaml
charts/ia-aip-frontend/values.yaml
config/default.json
infrastructure/main.tf

Attempt at re-instating Redis 6

Reverting multiple commits to re-instate Redis 6

---

app/controllers/hearing-requirements/hearing-requirements-summary-sections.ts
app/controllers/hearing-requirements/hearing-witness-names.ts
app/service/update-appeal-service.ts
app/utils/utils.ts
app/utils/validations/fields-validations.ts
locale/en.json
test/unit/controllers/hearing-requirements/check-and-send.test.ts
test/unit/controllers/hearing-requirements/hearing-witness-names.test.ts
test/unit/controllers/hearing-requirements/your-hearing-needs.test.ts
test/unit/utils/utils.test.ts
types/caseData.d.ts
types/index.d.ts
views/hearing-requirements/hearing-witness-names.njk

https://tools.hmcts.net/jira/browse/RIA-7415
* Update witness details to include given names and family name fields
* Update Controllers and views to use the updated witness details
* Ensure existing witness details model still works
* Unit tests
```
[ ] Yes
[x] No
```

RIA-7415 Split witness names to capture first and last names in AiP journey

---

app/assets/scss/_progress-bar.scss
app/assets/scss/application.scss
locale/en.json
package.json
views/appeal-application/appeal-out-of-country.njk
views/appeal-application/check-and-send.njk
views/appeal-application/home-office/letter-received.njk
views/appeal-application/home-office/letter-sent.njk
views/appeal-application/out-of-country/hr-eea.njk
views/appeal-application/out-of-country/hr-inside.njk
views/appeal-application/out-of-country/ooc-protection-departure-date.njk
views/appeal-application/sponsor-details/has-sponsor.njk
views/appeal-application/sponsor-details/sponsor-authorisation.njk
views/appeal-application/type-of-appeal.njk
views/ask-for-more-time/check-and-send.njk
views/components/progress-bar.njk
views/components/summary-list.njk
views/detail-viewers/view-ho-details.njk
views/eligibility/eligibility-question.njk
views/reasons-for-appeal/check-and-send-page.njk
views/templates/textarea-question-page.njk
yarn.lock

https://tools.hmcts.net/jira/browse/RIA-7834
PR incorporating following PRs:
https://github.com/hmcts/ia-aip-frontend/pull/989
https://github.com/hmcts/ia-aip-frontend/pull/984
https://github.com/hmcts/ia-aip-frontend/pull/987
https://github.com/hmcts/ia-aip-frontend/pull/986
https://github.com/hmcts/ia-aip-frontend/pull/985
https://github.com/hmcts/ia-aip-frontend/pull/983
https://github.com/hmcts/ia-aip-frontend/pull/981
```
[ ] Yes
[x] No
```

RIA-7834 Accessibility fix mass deployment

---

app/controllers/hearing-requirements/access-needs.ts
app/controllers/hearing-requirements/hearing-witness-names.ts
app/utils/utils.ts
test/unit/controllers/hearing-requirements/access-needs.test.ts
test/unit/controllers/hearing-requirements/hearing-witness-names.test.ts
test/unit/service/update-appeal-service.test.ts
types/index.d.ts

https://tools.hmcts.net/jira/browse/RIA-7875
- [Fix the problem of sonar](https://sonarcloud.io/summary/new_code?id=IAAPFR&pullRequest=972) including bug, code coverage and duplication
```
[ ] Yes
[X] No
```

RIA-7875 fix the sonar problem for the bug and code coverage

---

app/controllers/hearing-requirements/access-needs.ts
charts/ia-aip-frontend/Chart.yaml
test/unit/controllers/hearing-requirements/access-needs.test.ts
types/index.d.ts

https://tools.hmcts.net/jira/browse/RIA-7967
- Removed the global variable and retrieve common reference data in local function
- Upgraded the nodejs chart version to 3.0.0 because chart 2.4.14 is deprecated and failed in pipeline

RIA-7967 Submit hearing requirement failing in AIP demo Env

---

app/controllers/make-application/appeal-requests/change-hearing-type-application.ts
app/controllers/make-application/appeal-requests/setup-appeal-application-controllers.ts
app/data/application-types.ts
app/paths.ts
locale/en.json
test/unit/controllers/make-application/appeal-requests/change-hearing-type-application.test.ts
test/unit/controllers/make-application/appeal-requests/setup-appeal-application-controllers.test.ts
views/application-overview.njk

https://tools.hmcts.net/jira/browse/RIA-7781
- [x ] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)

RIA-7781 - New Application type- Change hearing type Missing for AIP

---

Jenkinsfile_nightly
package.json
test/java/build.gradle
test/java/config/fortify-client.properties
test/java/gradle/wrapper/gradle-wrapper.properties
yarn.lock

https://tools.hmcts.net/jira/browse/DIAC-105

DIAC-105 turning fortify on

---

app/controllers/detail-viewers.ts
app/controllers/hearing-requirements/hearings-feature-toggle.ts
app/data/events.ts
app/paths.ts
app/utils/timeline-utils.ts
locale/en.json
test/unit/controllers/detail-viewers.test.ts
test/unit/utils/timeline-utils.test.ts

[RIA-8416](https://tools.hmcts.net/jira/browse/RIA-8416)
- Show Notice of Adjourned Hearing on the timeline when available

RIA-8416 Notice of Adjourned Hearing on AIP

---

codecept.e2e.js
codecept.functional.ts
test/e2e-test/features/basic.feature
test/e2e-test/features/failed-payments.feature
test/e2e-test/features/full-e2e.feature
test/e2e-test/features/make-an-application.feature
test/e2e-test/features/start-to-decided.feature
test/e2e-test/helpers/failedTestHelper.js
test/e2e-test/helpers/navigationHelper.ts
test/e2e-test/pages/appeal-sent/appeal-sent.ts
test/e2e-test/pages/sign-in.ts
test/e2e-test/step_definitions/steps.ts
test/functional/bootstrap.ts
types/steps.d.ts

DIAC-228 nightly improvements

---

app/controllers/appeal-application/fee-support.ts
test/unit/controllers/fee-support.test.ts

https://tools.hmcts.net/jira/browse/RIA-8019
RIA-8019 Add unit test for sonar coverage

RIA-8019 Add unit test for sonar coverage

---

app/controllers/appeal-application/task-list.ts
app/utils/tasks-utils.ts
test/unit/controllers/task-list.test.ts
test/unit/utils/task-utils.test.ts

https://tools.hmcts.net/jira/browse/RIA-8019
RIA-8019 Add fee type option with dlrm flag

RIA-8019 Add fee type option with dlrm flag

---

app/controllers/detail-viewers.ts
app/data/constants.ts
app/data/events.ts
app/service/update-appeal-service.ts
app/utils/timeline-utils.ts
locale/en.json
test/unit/controllers/detail-viewers.test.ts
test/unit/service/update-appeal-service.test.ts
test/unit/utils/timeline-utils.test.ts
types/caseData.d.ts
types/index.d.ts

https://tools.hmcts.net/jira/browse/RIA-8199
Added R35 document for appellant FTPA application

RIA-8199 Added R35 document for appellant FTPA application

---

app/controllers/detail-viewers.ts
app/service/update-appeal-service.ts
app/utils/application-state-utils.ts
locale/en.json
test/unit/controllers/detail-viewers.test.ts
test/unit/utils/application-state-utils.test.ts
types/caseData.d.ts
types/index.d.ts

https://tools.hmcts.net/jira/browse/RIA-8207
HO timeline changes for rule 31 and rule 32

RIA-8207 HO timeline changes for rule 31 and rule 32

---

app/utils/event-deadline-date-finder.ts
test/unit/utils/event-deadline-date-finder.test.ts

https://tools.hmcts.net/jira/browse/RIA-8050
RIA-8050 Add out of country extra days

RIA-8050 Add out of country extra days

---

app/controllers/appeal-application/check-and-send.ts
app/controllers/appeal-application/help-with-fees.ts
app/controllers/appeal-application/upload-local-authority-letter.ts
locale/en.json
test/unit/controllers/check-and-send.test.ts
test/unit/controllers/help-with-fees.test.ts
views/appeal-application/fee-support/help-with-fees.njk
views/appeal-application/fee-support/upload-local-authority-letter.njk
views/components/evidence-list-with-dynamic-title.njk
views/components/radio-button-question-custom-legend-class.njk

https://tools.hmcts.net/jira/browse/RIA-8048
Fixed QA comments described in the Jira-link comment.

RIA-8048 qa-fixes

---

charts/ia-aip-frontend/Chart.yaml
charts/ia-aip-frontend/values.yaml

DIAC-268 Enable HPA and check memory settings Update Chart.yaml

---

app/controllers/appeal-application/confirmation-page.ts
locale/en.json
test/unit/controllers/confirmation-page.test.ts
views/confirmation-page.njk
yarn.lock

https://tools.hmcts.net/jira/browse/RIA-8679
Added conditions for confirmation page if appeal with and without remissions. Changed some existing values for confirmation page according to the ticket description comments.

RIA-8679 confirmation_page

---

locale/en.json
test/unit/utils/application-state-utils.test.ts

https://tools.hmcts.net/jira/browse/RIA-8050
RIA-8050 Fix typos

RIA-8050 Fix typos

---

app/controllers/appeal-application/check-and-send.ts
app/controllers/appeal-application/out-of-time.ts
app/paths.ts
locale/en.json
test/unit/controllers/check-and-send.test.ts
test/unit/controllers/out-of-time.test.ts
views/appeal-application/home-office/appeal-late.njk

This reverts commit 1b1f51abf9bbfb1716274ac8fa03807de5f86d11.
https://tools.hmcts.net/jira/browse/RIA-8052
Revert "RIA-8052 Modify check and send file uploader (#1055)"

Revert "RIA-8052 Modify check and send file uploader (#1055)"

---

app/controllers/appeal-application/confirmation-page.ts
test/unit/controllers/confirmation-page.test.ts
views/confirmation-page.njk

https://tools.hmcts.net/jira/browse/RIA-8679
Removed No remission condition in confirmation page

RIA-8679 remove_noRemission_condition

---

app/controllers/detail-viewers.ts
app/paths.ts
app/service/update-appeal-service.ts
app/utils/application-state-utils.ts
app/utils/event-deadline-date-finder.ts
app/utils/timeline-utils.ts
app/utils/utils.ts
locale/en.json
test/unit/controllers/detail-viewers.test.ts
test/unit/service/update-appeal-service.test.ts
test/unit/utils/application-state-utils.test.ts
test/unit/utils/event-deadline-date-finder.test.ts
test/unit/utils/timeline-utils.test.ts
test/unit/utils/utils.test.ts
types/caseData.d.ts
types/index.d.ts
views/application-overview.njk

https://tools.hmcts.net/jira/browse/RIA-8227
- update Tribunal Decision Rule 32 in AIP Timeline
- create and update the unit test

RIA-8227 update tribunal decision rule 32 AIP timeline

---

app/service/update-appeal-service.ts
app/utils/timeline-utils.ts
test/unit/utils/timeline-utils.test.ts
types/caseData.d.ts
types/index.d.ts

https://tools.hmcts.net/jira/browse/RIA-8211
- Quick fix the scenario 4
- update the logic of timeline
- update the unit test

RIA-8211 update tribunal decision rule 31 aip timeline v2

---

app/controllers/detail-viewers.ts
test/unit/controllers/detail-viewers.test.ts
views/templates/details-with-fees-viewer.njk

https://tools.hmcts.net/jira/browse/RIA-8051
RIA-8051 Fix details screen for Revocation of Protection and Deprivation of Citizenship  appeal types

RIA-8051 Fix details screen for RP and DC appeal types

---

app/controllers/appeal-application/confirmation-page.ts
config/default.json
locale/en.json
test/unit/controllers/confirmation-page.test.ts
views/confirmation-page.njk

https://tools.hmcts.net/jira/browse/RIA-8747
RIA-8747 Modify confirmation page when appeal is late.

RIA-8747 Modify confirmation page when appeal is late.

---

views/confirmation-page.njk

https://tools.hmcts.net/jira/browse/RIA-8747
RIA-8747 Fix header title

RIA-8747 Fix header title

---

app/controllers/appeal-application/check-and-send.ts
locale/en.json
test/unit/controllers/check-and-send.test.ts
views/appeal-application/check-and-send.njk

https://tools.hmcts.net/jira/browse/RIA-8729
RIA-8729 set button title for dlrm fee remission cases

RIA-8729 set button title for dlrm fee remission cases

---

app/service/update-appeal-service.ts
views/appeal-application/fee-support/steps-to-help-with-fees.njk

https://tools.hmcts.net/jira/browse/RIA-8069
https://tools.hmcts.net/jira/browse/RIA-8070
Fixed styles in fee help and mapping issues

RIA-8069_RIA-8070 ask_for_fee_remission

---

locale/en.json
views/ask-for-fee-remission/fee-support-refund.njk

https://tools.hmcts.net/jira/browse/RIA-8070
Fixed title in Refund 1st page and translation typo.

RIA-8070 fixing_QA_comments

---

locale/en.json

https://tools.hmcts.net/jira/browse/RIA-8764
RIA-8764 Add missing title

RIA-8764 Add missing title

---

app/controllers/detail-viewers.ts
app/utils/remission-utils.ts

https://tools.hmcts.net/jira/browse/RIA-8764
RIA-8764 Fix later remission option helpWithFees check

RIA-8764 Fix later remission option helpWithFees check

---

app/controllers/detail-viewers.ts
test/unit/controllers/detail-viewers.test.ts

https://tools.hmcts.net/jira/browse/RIA-8086
RIA-8086 Modify Fee support status

RIA-8086 Modify Fee support status

---

test/unit/utils/application-state-utils.test.ts

RIA-TASK - Add test to increase coverage

---

app/controllers/detail-viewers.ts
app/data/events.ts
app/service/update-appeal-service.ts
app/utils/timeline-utils.ts
locale/en.json
test/unit/controllers/detail-viewers.test.ts
test/unit/service/update-appeal-service.test.ts
test/unit/utils/timeline-utils.test.ts
types/caseData.d.ts
types/index.d.ts

https://tools.hmcts.net/jira/browse/RIA-8245
RIA-8245 Create  manage a fee update details and timeline

RIA-8245 Create  manage a fee update details and timeline

---

views/templates/textarea-question-page.njk

https://tools.hmcts.net/jira/browse/DIAC-364

DIAC-364 accessibility issue fixes

---

app/controllers/detail-viewers.ts
app/service/update-appeal-service.ts
app/utils/timeline-utils.ts
charts/ia-aip-frontend/Chart.yaml
test/unit/controllers/detail-viewers.test.ts
test/unit/service/update-appeal-service.test.ts
test/unit/utils/timeline-utils.test.ts
types/caseData.d.ts
types/index.d.ts

https://tools.hmcts.net/jira/browse/RIA-8245
RIA-8245 Add fee update remission section for appeals without remission

RIA-8245 Add fee update remission section for appeals without remission

---

test/e2e-test/features/full-e2e.feature
test/e2e-test/features/legal-rep-to-aip-noc.feature
test/e2e-test/features/make-an-application.feature
test/e2e-test/features/start-to-decided.feature
test/e2e-test/helpers/navigationHelper.ts
test/e2e-test/pages/legal-rep-create-case/legal-rep-create-case.ts
test/e2e-test/pages/start-representing-yourself/start-representing-yourself.ts
test/e2e-test/service/case-progression-service.ts

https://tools.hmcts.net/jira/browse/DIAC-422

DIAC-422 test fixes

---

locale/en.json

https://tools.hmcts.net/jira/browse/DIAC-423

DIAC-423 content fix

---

test/e2e-test/pages/appeal-sent/appeal-sent.ts

https://tools.hmcts.net/jira/browse/DIAC-425

DIAC-425 fix from DLRM release

---

test/e2e-test/pages/appeal-sent/appeal-sent.ts
test/e2e-test/pages/make-application/make-appeal-application.ts

DIAC-433 flakeyness fix

---

test/unit/utils/validations/fields-validations.test.ts

- remove duplicated method and fix the unit test problem after merging

RIA-TASK Fix SNL branch unit test issue

---

app/controllers/idam.ts
audit.json
charts/ia-aip-frontend/Chart.yaml

https://tools.hmcts.net/jira/browse/DIAC-515

DIAC-515 nightly fix

---

app/data/events.ts
app/utils/remission-utils.ts
test/unit/utils/remission-utils.test.ts

https://tools.hmcts.net/jira/browse/RIA-9197
Added 'Mark appeal as paid event', edited remission utils and tests for them.

RIA-9197 paid_event

---

app/utils/regular-expressions.ts
test/unit/utils/validations/fields-validations.test.ts

https://tools.hmcts.net/jira/browse/DIAC-523

DIAC-523 Allow space in middle of postcode (regex)

---

app/utils/application-state-utils.ts
test/unit/utils/application-state-utils.test.ts

https://tools.hmcts.net/jira/browse/RIA-9221
RIA-9221 Fix pendingPayment with record decission screen

RIA-9221 Fix pendingPayment with record decission screen

---

app/controllers/application-overview.ts
charts/ia-aip-frontend/Chart.yaml
test/unit/controllers/application-overview.test.ts

https://tools.hmcts.net/jira/browse/RIA-9221
RIA-9331 Remove payment link when remission is approved or partiallyapproved

RIA-9331 Remove payment link when remission is approved or partiallyapproved

---

test/e2e-test/service/authentication-service.ts
test/e2e-test/service/case-progression-service.ts

DIAC-123 nightly crossbrowser fix

---

package.json
yarn.lock

[DIAC-595](https://tools.hmcts.net/jira/browse/DIAC-595)
Add micromatch to resolutions fixing [CVE-2024-4067](https://nvd.nist.gov/vuln/detail/CVE-2024-4067)

DIAC-366 micromatch

---

app/service/update-appeal-service.ts
app/utils/application-state-utils.ts
locale/en.json
test/unit/service/update-appeal-service.test.ts
test/unit/utils/application-state-utils.test.ts
types/caseData.d.ts
types/index.d.ts

https://tools.hmcts.net/jira/browse/RIA-9534
Updated description for record remission decision

RIA-9534 Updated description for record remission decision

---

test/e2e-test/pages/legal-rep-create-case/legal-rep-create-case.ts
test/e2e-test/service/case-progression-service.ts

See [DIAC-594](https://tools.hmcts.net/jira/browse/DIAC-594)

DIAC-594 updating test post refdata release

---

test/e2e-test/pages/legal-rep-create-case/legal-rep-create-case.ts
test/e2e-test/service/case-progression-service.ts

See [DIAC-594](https://tools.hmcts.net/jira/browse/DIAC-594)

DIAC-594 updating test post lr family name addition

---

app/controllers/detail-viewers.ts
app/utils/application-state-utils.ts
test/unit/controllers/detail-viewers.test.ts

See [RIA-9542](https://tools.hmcts.net/jira/browse/RIA-9542)
RIA-9542 remove nullcheck and add no action details refund

RIA-9542 remove nullcheck and add no action details refund

---

Jenkinsfile_CNP

Publish Unit test and Code coverage reports

RIA-TASK Publish Unit test and Code coverage reports

---

app/utils/application-state-utils.ts

https://tools.hmcts.net/jira/browse/RIA-9547
Fixed late remission timeline
Removed timeline description from various states

RIA-9547 Fixed late remission timeline

---

app/controllers/detail-viewers.ts
app/service/update-appeal-service.ts
locale/en.json
test/unit/controllers/detail-viewers.test.ts
test/unit/service/update-appeal-service.test.ts
types/caseData.d.ts
types/index.d.ts

See [RIA-9546](https://tools.hmcts.net/jira/browse/RIA-9546)
RIA-9546 add feeUpdateReason different text

RIA-9546 add feeUpdateReason different text

---

app/controllers/appeal-application/confirmation-page.ts
app/controllers/detail-viewers.ts
app/utils/timeline-utils.ts

RIA-TASK fix sonar maintainability

RIA-TASK fix sonar maintainability

---

app/controllers/appeal-application/confirmation-page.ts

RIA-TASK fix sonar maintainability v2

RIA-TASK fix sonar maintainability v2

---

app/service/update-appeal-service.ts
test/unit/service/update-appeal-service.test.ts

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
RIA-0001 protect fields for feature toggle off

RIA-0001 protect fields for feature toggle off

---

app/controllers/appeal-application/confirmation-page.ts
test/unit/controllers/confirmation-page.test.ts

https://tools.hmcts.net/jira/browse/RIA-9567
Hide pay appeal link

RIA-9567 Hide pay appeal link

---

app/controllers/appeal-application/check-and-send.ts
app/controllers/appeal-application/confirmation-page.ts
test/unit/controllers/check-and-send.test.ts
test/unit/controllers/confirmation-page.test.ts

https://tools.hmcts.net/jira/browse/RIA-9567
Updated refundConfirmation invoke location

RIA-9567 Updated refundConfirmation invoke location

---

app/service/update-appeal-service.ts

https://tools.hmcts.net/jira/browse/RIA-9581
Fix maintainability

RIA-9580 Fix maintainability

---

app/service/update-appeal-service.ts
yarn.lock

RIA-1234 sonar_cloud_issues_fix

---

app/service/update-appeal-service.ts

Reverts hmcts/ia-aip-frontend#1228

Revert "RIA-TASK Fix Sonar cloud issue for CMA requirements"

---

app/service/update-appeal-service.ts

Reverts hmcts/ia-aip-frontend#1227

Revert "RIA-1234 sonar_cloud_issues_fix"

---

app/service/update-appeal-service.ts

RIA-1122 sonar_cloud_issues_fix

---

app/service/update-appeal-service.ts
app/utils/utils.ts

Fix sonar cloud issues with Severity.

RIA-1123 reducing_severity

---

test/unit/service/update-appeal-service.test.ts

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

RIA-3333 remove unused import

---

test/unit/service/update-appeal-service.test.ts

RIA-2222 Fix code coverage

---

test/unit/controllers/home-office-details-upload-decision-letter.test.ts

https://tools.hmcts.net/jira/browse/DIAC-703
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

DIAC-703 - update test to stub feature flag

---

README.md

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

DIAC-123 - test push

---

charts/ia-aip-frontend/Chart.yaml
charts/ia-aip-frontend/values.preview.template.yaml
charts/ia-aip-frontend/values.yaml

See [DIAC-1410](https://tools.hmcts.net/jira/browse/DIAC-1410)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?

DIAC-1410 - remove aip service maintenance banner
