hmcts/ia-aip-frontend

app/controllers/idam.ts
app/utils/url-utils.ts
test/unit/utils/url-utils.test.ts

When you were redirect back from idam on any environment other than localhost the redirect was not working. This was because it was hardcoded to https://localhost:3000/redirectUrl. It needs to be built from the protocol and host in the request to allow for all the different urls we use in an environment.

Set redirect url based on the request url not hard coded to localhost

---

app/assets/scss/_task-list.scss
app/controllers/home-office-details.ts
views/appeal-application/task-list.njk

https://tools.hmcts.net/jira/browse/RIA-2225
Task list tags for saved and completed sections should show:
- 'saved' with a grey background if section NOT completed but some questions answered
- 'saved' with a grey background if section completed and should activate next task/section
```
[ ] Yes
[ X ] No
```

Task list tags

---

app/controllers/check-and-send.ts
app/controllers/contact-details.ts
app/controllers/home-office-details.ts
app/controllers/personal-details.ts
app/controllers/type-of-appeal.ts
app/data/appeal-types.ts
app/routes.ts
app/service/ccd-service.ts
app/service/update-appeal-service.ts
app/utils/fields-validations.ts
app/utils/tasks-utils.ts
locale/en.json
test/unit/controllers/check-and-send.test.ts
test/unit/controllers/contact-details.test.ts
test/unit/controllers/enter-address.test.ts
test/unit/controllers/enter-date.test.ts
test/unit/controllers/enter-postcode.test.ts
test/unit/controllers/get-name-page.test.ts
test/unit/controllers/home-office-details.test.ts
test/unit/controllers/nationatily-page.test.ts
test/unit/controllers/postcode-lookup.test.ts
test/unit/controllers/type-of-appeal.test.ts
test/unit/mockData/mock-appeal.ts
test/unit/service/ccd-service.test.ts
test/unit/service/update-appeal-service.test.ts
test/unit/utils/task-utils.test.ts
types/index.d.ts
views/appeal-application/contact-details.njk

https://tools.hmcts.net/jira/browse/RIA-1963
https://tools.hmcts.net/jira/browse/RIA-1965
https://tools.hmcts.net/jira/browse/RIA-2165
Adds Backwards mapping from ccd for contactDetails  and appealType
**RIA-1963:**
Makes contact details validation more intelligent to allow certain cases in the checkboxes and inputs.
Adds ability to:
- Save contact details using the new format with subscribers
- Submit the appeal to ccd using the correct event
Other:
Reworked contact details page and contact details object structure to introduce two new booleans used to trigger conditional expressions and error messages, populated from the checkboxes.
**RIA-1965:**
Adds ability to:
- Triggers a Submit event to submit the appeal.
**RIA-2165:**
Adds ability to:
- Submit the appeal to ccd using the correct …

RIA-1963 &  RIA-1965 : ContactDetails & Appeal Submission to CCD

---

app/controllers/contact-details.ts
app/utils/fields-validations.ts
app/utils/regular-expressions.ts
test/unit/utils/fields-validations.test.ts

Removing whitespaces before validation on mobileNumbers.
Fixing Regex validation for mobile phone numbers (UK only).
```
[ ] Yes
[ x] No
```

Fixing Regex validation for mobile phone numbers (UK only).

---

charts/ia-aip-frontend/requirements.yaml
charts/ia-aip-frontend/values.preview.template.yaml

When the pr environment deploys the URL changes each time. As the
redirect URL sent to idam is checked against a whitelist this needs to
be added to the whitelist for each PR environment.

Fix pr environment

---

app/controllers/check-and-send.ts
locale/en.json
test/unit/mockData/mock-appeal.ts

Fix: Check and send page showing values rather than the name of the a…ppeal type.
Renaming revocation to the correct value.
```
[ ] Yes
[x ] No
```

Fix: Type of appeal display

---

app/utils/fields-validations.ts

When the user enters their address manually they may not know their postcode so we cannot make the field mandatory. 
Disable validation when the user does not enter a postcode.
https://tools.hmcts.net/jira/browse/RIA-1962

Disable requiring a postcode 

---

app/controllers/check-and-send.ts
app/controllers/contact-details.ts
app/controllers/home-office-details.ts
app/controllers/personal-details.ts
app/controllers/type-of-appeal.ts
app/utils/url-utils.ts
locale/en.json
test/unit/controllers/check-and-send.test.ts
test/unit/controllers/contact-details.test.ts
test/unit/controllers/enter-address.test.ts
test/unit/controllers/enter-dob.test.ts
test/unit/controllers/enter-name-page.test.ts
test/unit/controllers/home-office-details.test.ts
test/unit/controllers/nationatily-page.test.ts
test/unit/controllers/type-of-appeal.test.ts
types/index.d.ts

https://tools.hmcts.net/jira/browse/RIA-2281
https://tools.hmcts.net/jira/browse/RIA-2282
**RIA-2281:** Fixes Change links from CYA page, when clicking in a 'change' link in CYA once the data is changed it should redirect back to the CYA page.
Added tests to cover all scenarios
**RIA-2282:** Splits contact details summary row in Address and contact details as they are different sections and data is captured at different stages.
```
[ ] Yes
[ x] No
```

RIA-2281 & RIA-2282: Change link in CYA page and Re-design of summary rows

---

app/controllers/personal-details.ts
test/unit/controllers/enter-address.test.ts
views/appeal-application/personal-details/enter-address.njk

The back link on the manual address page was missing. There is not a
single page you come from for the manual address so store your source in
the session and set that.
https://tools.hmcts.net/jira/browse/RIA-2355
```
[ ] Yes
[X] No
```

RIA-2355 Back link on manual address page

---

test/functional/bootstrap.ts

Shutdown the test servers before calling process.exit(). This should be cleaner than just killing them all.

Shutdown test servers

---

app/controllers/contact-details.ts
app/controllers/personal-details.ts
app/controllers/type-of-appeal.ts
test/unit/controllers/contact-details.test.ts
test/unit/controllers/enter-address.test.ts
test/unit/controllers/enter-dob.test.ts
test/unit/controllers/enter-name-page.test.ts
test/unit/controllers/home-office-details.test.ts
test/unit/controllers/nationatily-page.test.ts
test/unit/controllers/type-of-appeal.test.ts

Refactoring save for later logic
- if 'save for later' is clicked but body is empty, 'submitEvent' should not be called.
- refactoring unit tests
```
[ ] Yes
[ X ] No
```

Refactoring 'save for later' logic

---

Jenkinsfile_CNP
app/setupSecrets.ts
charts/ia-aip-frontend/values.preview.template.yaml
charts/ia-aip-frontend/values.yaml
infrastructure/main.tf

This app is currently using the sscs s2s secret. It should not be and we
need a task to fix this. As the new way we load secrets can only load
them from vault copied the sscs s2s secret to ia vault for now.
https://tools.hmcts.net/jira/browse/RIA-2414

RIA-2414 Setup AKS

---

app/app.ts
app/controllers/appeal-application/task-list.ts
app/controllers/idam.ts
app/routes.ts
app/session.ts
config/custom-environment-variables.json
config/default.json
config/development.json
config/test.json
package.json
test/e2e-test/pages/helper-functions.ts

- Runs tests as NODE_ENV test to pick up per-environment configuration.
- Removes the session logger and adds logic to allow session logger under dev environment only when env property "useLogger" is set.
```
[ ] Yes
[x ] No
```

Clean up: Running tests under NODE_ENV=test

---

app/middleware/session-middleware.ts
test/unit/middleware/session-middleware.test.ts

We were redirecting to the start page if you were not logged in.
If you had a session but it had expired we had code that noticed the
session had expired and removed the session cookie then redirected you
to the start page. Change it to redirect you to the login page.

RIA-2482 Having to go to the start page twice

---

app/utils/application-state-utils.ts
app/utils/event-deadline-date-finder.ts
locale/en.json
test/unit/utils/application-state-utils.test.ts

https://tools.hmcts.net/jira/browse/RIA-2741
Adding content for awaitingRespondentEvidence state on overview's page 'do next' component
```
[ ] Yes
[ X ] No
```

RIA-2741: Overview page copy changes for awaitingRespondentEvidence

---

app/utils/jwt-utils.ts
test/unit/utils/jwt-utils.test.ts

We were miss calculating if the s2s token had expired so it was never getting refreshed.

Fix refreshing s2s token

---

app/utils/jwt-utils.ts
test/unit/utils/jwt-utils.test.ts

for processes to complete once the token has been checked. This was
being taken off of current time so we were extending the time a token
was valid for. Added it to current time to reduce the time a token is
valid for. Also increased the offset to 5 minutes just to make sure we
are never using an expired token.

When we check a s2s token to see if it is still valid we allow an offset

---

app/handlers/error-handler.ts
test/unit/handlers/error-handler.test.ts

Previously we showed different error pages for different content types.
We only produce html and were causing ourselves issues if an accept
header was not set.

Simplify error pages

---

app/controllers/appeal-application/out-of-time.ts
app/controllers/reasons-for-appeal/check-and-send.ts
app/controllers/reasons-for-appeal/reason-for-appeal.ts
app/service/document-management-service.ts
app/service/update-appeal-service.ts
test/unit/controllers/out-of-time.test.ts
test/unit/controllers/reasons-for-appeal/check-and-send.test.ts
test/unit/controllers/reasons-for-appeal/reason-for-appeal.test.ts
test/unit/controllers/reasons-for-appeal/supporting-evidence-upload.test.ts
test/unit/service/update-appeal-service.test.ts
types/index.d.ts
views/components/evidence-list.njk
views/components/timeout-modal.njk

https://tools.hmcts.net/jira/browse/RIA-2770
- Fixing empty link accessibility bug
- Refactoring Evidences definition as an array instead of object on reasonsForAppeal
- Removing id on Evidence interface as it is not used and is just adding confusion
```
[ ] Yes
[ X ] No
```

Ria 2770: accessibility empty link bug

---

app/app.ts
app/controllers/appeal-application/out-of-time.ts
app/controllers/reasons-for-appeal/reason-for-appeal.ts

The multipart forms were being processed after our XSS middleware. This
meant any text fields on pages that also contained a file upload (only
place at the moment is the reasons for a late appeal page) were not
being filtered for XSS exploits.
Moved the multipart form middleware to be before the XSS middleware in
the app.js file. This does mean that is is registered for all endpoints
but uses Multer which says in the docs it will not process any form that
is not multipart.
https://tools.hmcts.net/jira/browse/RIA-2897

RIA-2897 Cross site scripting - 'late appeal' page

---

test/functional/features/reason-for-appeal.feature
views/reasons-for-appeal/check-and-send-page.njk

https://tools.hmcts.net/jira/browse/RIA-2808
- Fixes CTA in Reasons for appeal CYA page.
- Changed from Save and continue to Send.
```
[ ] Yes
[ x] No
```

RIA-2808: Fixes CTA in Reasons for appeal CYA page.

---

app/controllers/reasons-for-appeal/check-and-send.ts
app/controllers/reasons-for-appeal/reason-for-appeal.ts
test/functional/features/reason-for-appeal.feature

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1190&projectKey=RIA&view=detail&selectedIssue=RIA-2902
fixed service error page when click no on supporting evidence
```
[ ] Yes
[ x ] No
```

RIA-2902-supporting-evidence-page-fix

---

app/app.ts

https://tools.hmcts.net/jira/browse/RIA-2790
Fixes an issue where:
Content Security Policy was refusing to apply inline style because:
"it violates the following Content Security Policy directive: "style-src 'self'". "
This commit adds he 'unsafe-inline' to the style-src content security policy
```
[ ] Yes
[x ] No
```

RIA-2790: Content Security Policy was refusing to apply inline style

---

Jenkinsfile_CNP

Enable prod builds by removing the config from Jenkinsfile_CNP that stops them.

Enable prod builds by removing the config from Jenkinsfile_CNP that stops them.

---

charts/ia-aip-frontend/Chart.yaml
charts/ia-aip-frontend/requirements.yaml

N/A
- Bumped ia-aip-frontend chart version
- Moved to bitnami charts repository and upgraded redis to version 10.0.0
```
[ ] Yes
[ x] No
```

Moved to Bitnami charts Repository and upgraded redis to version 10.0.0

---

app/config/idam-config.ts
app/controllers/idam.ts
app/utils/url-utils.ts
test/e2e-test/features/basic.feature
test/e2e-test/pages/sign-in.ts
test/mock/idam/services/register-page.js
test/unit/utils/url-utils.test.ts
views/eligibility/eligible-page.njk

After the user has answered the eligibility questions redirect them to
the IDAM self registration page rather than the login page. If they
click the I already have an account link then direct them to the login
page.
https://tools.hmcts.net/jira/browse/RIA-2798
```
[ ] Yes
[X] No
```

RIA-2798 Redirect to IDAM register page

---

app/controllers/appeal-application/check-and-send.ts
app/controllers/ask-for-more-time/ask-for-more-time.ts
app/controllers/reasons-for-appeal/check-and-send.ts
app/utils/utils.ts
package.json
test/e2e-test/pages/ask-for-more-time/ask-for-more-time.ts
test/unit/controllers/ask-for-more-time.test.ts
test/unit/controllers/check-and-send.test.ts
test/unit/controllers/reasons-for-appeal/check-and-send.test.ts
test/unit/utils/utils.test.ts
yarn.lock

An appellant can add new lines and space indents to an answer in a
textarea. When this was being displayed on the CYA page it lost that
formatting. This has been fixed for
- reasons for appeal
- reason for time extension
- reasons for late appeal
https://tools.hmcts.net/jira/browse/RIA-3216
```
[ ] Yes
[X] No
```

RIA-3216 Fix answer layout on CYA pages

---

app/controllers/ask-for-more-time/ask-for-more-time.ts
app/data/states.ts
app/service/update-appeal-service.ts
app/utils/application-state-utils.ts
app/utils/timeline-utils.ts
app/utils/utils.ts
locale/en.json
test/e2e-test/pages/overview-page/overview-page.ts
test/e2e-test/pages/sign-in.ts
test/functional/features/ask-for-more-time.feature
test/functional/features/overview-page.feature
test/mock/ccd/mock-case-data/data/clarifying-questions-with-time-extensions.js
test/mock/ccd/mock-case-data/index.js
test/mock/ccd/services/loadCases.js
test/mock/idam/services/getDetails.js
test/mock/idam/services/getODetails.js
test/unit/middleware/journeyAllowed-middleware.test.ts
test/unit/service/update-appeal-service.test.ts
test/unit/utils/utils.test.ts
types/index.d.ts
views/clarifying-questions/question-page.njk
views/templates/textarea-question-page.njk

https://tools.hmcts.net/jira/browse/RIA-2976
https://tools.hmcts.net/jira/browse/RIA-3153
https://tools.hmcts.net/jira/browse/RIA-3157
Removes unnecessary array filtering every time a page that contained …ask for more time was loaded.
Moved inflight ask for more time to the update appeal service so it's loaded whenever loadAppeal is called, this will become useful when we update the session after a submit event using the loadAppeal() and the object returned by CCD.
Fixes and updates tests
```
[ ] Yes
[x ] No
```

RIA-2976 & RIA-3153 & RIA-3157: Time Extensions for CMARequirements & Clarifying Questions

---

app/controllers/clarifying-questions/check-and-send.ts
app/data/events.ts
app/data/states.ts
app/paths.ts
app/service/update-appeal-service.ts
app/utils/application-state-utils.ts
app/utils/event-deadline-date-finder.ts
app/utils/timeline-utils.ts
config/default.json
locale/en.json
test/e2e-test/features/basic.feature
test/e2e-test/pages/common/common.ts
test/e2e-test/service/case-progression-service.ts
test/e2e-test/service/ccd-service.ts
test/functional/features/clarifying-questions.feature
test/unit/controllers/clarifying-questions/check-and-send.test.ts
test/unit/utils/application-state-utils.test.ts

https://tools.hmcts.net/jira/browse/RIA-2894
- To do next to include a description when appellant has sent answers for CQ
- Timeline includes now link to 'Your answers'
- CYA page to include 'Your answers'
```
[ ] Yes
[ X ] No
```

Ria 2894: CQ submitted timeline

---

Jenkinsfile_CNP
security.sh

Command line -d switch is obsolete, caused error on latest run, it's replaced with -daemon 
Also removed /dev/null output redirect, causing error on the local run although not stopping the run
Severity for console output set to Medium

Ria 6151 nightly build security scan issue

---

app/app.ts

https://tools.hmcts.net/jira/browse/RIA-6368
Updated CSP headers to loosen allowed domains for gov.uk and GA
```
[ ] Yes
[X] No
```

RIA-6368: Fixed csp error highlighted by Dynatrace report.

---

app/controllers/application-overview.ts
app/utils/progress-bar-utils.ts
app/utils/timeline-utils.ts
test/unit/utils/progress-bar.test.ts

[RIA-6596](https://tools.hmcts.net/jira/browse/RIA-6596)
- Made payment details appeal in the timeline after payment's made
- Made the first step in the progress bar be ticked when payment is made
```
[ ] Yes
[x] No
```

RIA-6596 Progress bar and timeline after AIP payment

---

app/controllers/detail-viewers.ts

[RIA-6572](https://tools.hmcts.net/jira/browse/RIA-6572)
- Made the frontend look for `endAppealAutomatically` tag as well as `endAppeal` when looking for documents generated for the end of the appeal (when clicking on _Notice of Ended Appeal_)
```
[ ] Yes
[x] No
```

RIA-6572 endAppealAutomatically document tag

---

locale/en.json
test/unit/utils/application-state-utils.test.ts

[https://tools.hmcts.net/jira/browse/RIA-6114](https://tools.hmcts.net/jira/browse/RIA-6114)
- Change link to lead to FTPA documents instead of appeal decision documents when FTPA is decided
```
[ ] Yes
[x] No
```

RIA-6114 link to FTPA docs overview page

---

app/controllers/detail-viewers.ts
app/utils/timeline-utils.ts
locale/en.json
test/unit/utils/timeline-utils.test.ts

https://tools.hmcts.net/jira/browse/RIA-6959
* Remove Home Office application decision event from timeline
* Fetch the hearing centre email in the Home office application details dynamically based on the appeal's hearing centre
```
[ ] Yes
[x] No
```

RIA-6959 Updates to Home Office Make application event timeline and details

---

app/controllers/application-overview.ts
app/data/events.ts
app/service/update-appeal-service.ts
app/utils/application-state-utils.ts
app/utils/timeline-utils.ts
locale/en.json
test/unit/controllers/application-overview.test.ts
test/unit/utils/timeline-utils.test.ts
types/caseData.d.ts
types/index.d.ts
views/application-overview.njk

https://tools.hmcts.net/jira/browse/RIA-7056
* Added transferToUt content for toDoNext section of overview page
* Dynamically returned correct dict for doThisNext for ended state depending on if utAppealReferenceNumber is present
* Added utility to check if appeal ended state reached via transferToUT event
* Added transferToUT event for timeline
* Added markAsReadyForUtTransfer event
* Added markAsReadyForUtTransfer event to appealArgument section
* Added utAppealReferenceNumber to appeal interface
* Added utAppealReferenceNumber to service class so that it can be read from case data
* Updates tests
AiP overview page and timeline when appeal is in ended state after being transferred to UT
AiP overview page (doThisNext) section updates only when there is a change in case state. Unlike the …

RIA-7056 Transfer to UT overview page toDoNext and timeline sections
